### ISSUE TITLE
Brunch postinstall failure

### ISSUE THREAD

**Issue by adstastic** [brunch/brunch#1015]
Hi,

I'm installing brunch on Ubuntu 14.04 and I get the following output:

```bash
$ npm install brunch
npm WARN optional dep failed, continuing fsevents@0.3.8
-
> brunch@1.8.5 postinstall /cath/homes2/zcapamu/webserver/cath-chopping-viewer/node_modules/brunch
> node -e "require('fs').readdir('lib',function(e){e&&require('child_process').exec('npm run prepublish')})"

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! brunch@1.8.5 postinstall: `node -e "require('fs').readdir('lib',function(e){e&&require('child_process').exec('npm run prepublish')})"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brunch@1.8.5 postinstall script.
npm ERR! This is most likely a problem with the brunch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -e "require('fs').readdir('lib',function(e){e&&require('child_process').exec('npm run prepublish')})"
npm ERR! You can get their info via:
npm ERR!     npm owner ls brunch
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-28-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "brunch"
npm ERR! cwd /cath/homes2/zcapamu/webserver/cath-chopping-viewer
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /cath/homes2/zcapamu/webserver/cath-chopping-viewer/npm-debug.log
npm ERR! not ok code 0
```

I get the same output with:
* `sudo npm install brunch` 
*  logging in as root and trying `npm install brunch` 
* `npm install https://github.com/brunch/brunch/tarball/master`
* all of the above with the `-g` flag

**Comment by adstastic** [comment]
It seems the errors happen soon after the postinstall script starts running. 
The **npm-debug.log** is too large to post on here so here it is from the postinstall onwards:
```
9470 info install brunch@1.8.5
9471 info postinstall brunch@1.8.5
9472 verbose unsafe-perm in lifecycle true
9473 info brunch@1.8.5 Failed to exec postinstall script
9474 verbose node_modules/brunch unbuild
9475 warn This failure might be due to the use of legacy binary "node"
9476 warn For further explanations, please read
/usr/share/doc/nodejs/README.Debian
9477 info preuninstall brunch@1.8.5
9478 info uninstall brunch@1.8.5
9479 verbose true,/cath/homes2/zcapamu/webserver/cath-chopping-viewer/node_modules,/cath/homes2/zcapamu/webserver/cath-chopping-viewer/node_modules unbuild brunch@1.8.5
9480 verbose /cath/homes2/zcapamu/webserver/cath-chopping-viewer/node_modules/.bin,[object Object] binRoot
9481 info postuninstall brunch@1.8.5
9482 error brunch@1.8.5 postinstall: `node -e "require('fs').readdir('lib',function(e){e&&require('child_process').exec('npm run prepublish')})"`
9482 error Exit status 1
9483 error Failed at the brunch@1.8.5 postinstall script.
9483 error This is most likely a problem with the brunch package,
9483 error not with npm itself.
9483 error Tell the author that this fails on your system:
9483 error     node -e "require('fs').readdir('lib',function(e){e&&require('child_process').exec('npm run prepublish')})"
9483 error You can get their info via:
9483 error     npm owner ls brunch
9483 error There is likely additional logging output above.
9484 error System Linux 3.16.0-28-generic
9485 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "brunch"
9486 error cwd /cath/homes2/zcapamu/webserver/cath-chopping-viewer
9487 error node -v v0.10.25
9488 error npm -v 1.4.21
9489 error code ELIFECYCLE
9490 verbose exit [ 1, true ]
```

**Comment by adstastic** [comment]
Just for clarification: this issue is not closed. I mistakenly closed it 3 days ago.

**Comment by es128** [comment]
How did you install node on this machine? It appears to be complaining that you have no `node` binary available in your `PATH`. 

What happens when you run that `node -e` script manually?

**Comment by adstastic** [comment]
I installed nodejs using apt-get. Running the node -e script manually doesn't do anything, or gives undefined variable errors.

I was trying to install another npm package which wasn't working, and one of the suggestions was to remove node using apt-get and create a symlink from `/usr/bin/nodejs` to `/usr/bin/node`, after which the install worked fine.

The error I now get with trying to install Brunch is:
```
$ sudo npm install -g brunch
npm ERR! Error: Attempt to unlock brunch, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/share/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:30:7
npm ERR!     at /usr/lib/nodejs/lockfile.js:161:38
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-28-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "brunch"
npm ERR! cwd /cath/homes2/zcapamu/webserver/cath-chopping-viewer
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!  { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES', path: 'npm-debug.log' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-28-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "brunch"
npm ERR! cwd /cath/homes2/zcapamu/webserver/cath-chopping-viewer
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open 'npm-debug.log'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /cath/homes2/zcapamu/webserver/cath-chopping-viewer/npm-debug.log
npm ERR! not ok code 0
```

**Comment by es128** [comment]
Don't use the one from apt at all, uninstall it. 

Use the installer from nodejs.org

**Comment by adstastic** [comment]
Thanks!
