### ISSUE TITLE
TypeError when npm is enabled

### ISSUE THREAD

**Issue by lpil** [brunch/brunch#1022]
With this in my config:

```
  npm: {
    enabled: true
  }
```

I get this error

```
    sourcePos = wrapped.indexOf(compiled);
                       ^

TypeError: Cannot read property 'indexOf' of undefined
  at updateMap (/Users/louis/roli/ivy/node_modules/brunch/lib/fs_utils/source_file.js:26:24)
  at updateCache (/Users/louis/roli/ivy/node_modules/brunch/lib/fs_utils/source_file.js:63:16)
  at /Users/louis/roli/ivy/node_modules/brunch/lib/fs_utils/source_file.js:83:9
  at /Users/louis/roli/ivy/node_modules/brunch/lib/fs_utils/pipeline.js:138:14
  at stop (/Users/louis/roli/ivy/node_modules/brunch/node_modules/deppack/lib/deppack.js:166:12)
  at /Users/louis/roli/ivy/node_modules/brunch/node_modules/deppack/lib/deppack.js:99:18
  at /Users/louis/roli/ivy/node_modules/brunch/node_modules/async-each/index.js:20:18
  at /Users/louis/roli/ivy/node_modules/brunch/node_modules/deppack/lib/deppack.js:88:18
  at /Users/louis/roli/ivy/node_modules/brunch/node_modules/deppack/node_modules/browser-resolve/index.js:254:24
  at /Users/louis/roli/ivy/node_modules/brunch/node_modules/deppack/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:14
  at process (/Users/louis/roli/ivy/node_modules/brunch/node_modules/deppack/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
  at ondir (/Users/louis/roli/ivy/node_modules/brunch/node_modules/deppack/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
  at load (/Users/louis/roli/ivy/node_modules/brunch/node_modules/deppack/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
  at onex (/Users/louis/roli/ivy/node_modules/brunch/node_modules/deppack/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
  at /Users/louis/roli/ivy/node_modules/brunch/node_modules/deppack/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
  at FSReqWrap.oncomplete (fs.js:82:15)
```

```
    "brunch": "^1.8.5",
```
```
louis ~ $ node -v
v4.1.1
```

Thanks,
Louis

**Comment by tregagnon** [comment]
I am getting the same error. With Node.js 0.12.7.

**Comment by paulmillr** [comment]
Let's move to gh-1023.

**Comment by liveforeverx** [comment]
I'm getting this error after `npm install` and after some adding in dependencies, and now I do not know, nor how to find, why it happen, what to change back, that it doesn't happen, after trying to uncomment code, which I written, it simply doesn't help. For me, somebody who isn't JS developer, this is really undebugable.

**Comment by lpil** [comment]
Hi Dmitry. Could you try bumping your brunch version to 2.1.1 in your brunch config?

**Comment by liveforeverx** [comment]
@lpil : Yes, error is more descriptive now:

```
error: Initialization error - Error: ENOENT: no such file or directory, open '[....]/node_modules/angular2/index.js'
```

`index.js` is not defined here, but, I do not understand, why it tries to find `index.js`

**Comment by liveforeverx** [comment]
@lpil But, if I copy needed JS files and remove angular2 from npm, than I can at least avoid a problem. Thanks!

**Comment by lpil** [comment]
Sorry I couldn't help more, my JS is iffy at best!

**Comment by liveforeverx** [comment]
I've tried to use js files directly in vendor(copied needed files and remove dependencies, which was giving a problems)and now another error, which gives no information, what going wrong:

```javascript
throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received false
  at assertPath (path.js:9:11)
  at Object.posix.join (path.js:480:5)
```
