### ISSUE TITLE
Unable to download any skeleton

### ISSUE THREAD

**Issue by dsiddharth2** [brunch/brunch#1106]
$ brunch new gh:oddpixel/brunch-steak test-project
11 Jan 19:58:25 - log: Cloning git repo "https://github.com/brunch/dead-simple" to "gh:oddpixel/brunch-steak"...
11 Jan 19:58:35 - log: Created skeleton directory layout
11 Jan 19:58:35 - log: Installing packages...
/usr/local/lib/node_modules/brunch/node_modules/init-skeleton/index.js:42
  process.chdir(rootPath);
          ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at install (/usr/local/lib/node_modules/brunch/node_modules/init-skeleton/index.js:42:11)
    at /usr/local/lib/node_modules/brunch/node_modules/init-skeleton/index.js:135:11
    at cb (/usr/local/lib/node_modules/brunch/node_modules/init-skeleton/node_modules/ncp/lib/ncp.js:255:23)
    at onError (/usr/local/lib/node_modules/brunch/node_modules/init-skeleton/node_modules/ncp/lib/ncp.js:247:12)
    at /usr/local/lib/node_modules/brunch/node_modules/init-skeleton/node_modules/ncp/lib/ncp.js:159:16
    at FSReqWrap.oncomplete (fs.js:82:15)

npm -version
2.14.12

brunch -version
2.1.3

**Comment by paulmillr** [comment]
What is your node.js version? Could you try updating to the latest node?

**Comment by paulmillr** [comment]
Actually the syntax is invalid. It should be: `brunch new test-project -s gh:oddpixel/brunch-steak`

**Comment by dsiddharth2** [comment]
Thanks a lot.
