### ISSUE TITLE
Requiring JSON is broken in 2.5.0

### ISSUE THREAD

**Issue by colinbate** [brunch/brunch#1236]
### Description

There is an exception thrown when using 2.5.0 to build a project which references the node `crypto` package. The underlying cause is the requiring of a `.json` file which is causing an exception in `source_file` because `isNpmJSON` is undefined.

Below is the information from my test project to reproduce it. It is only one line added to the dead simple skeleton.

The reason that this is happening is that building requires `watch.js` which requires `fs_utils/index.js` which requires `fs_utils/file_list.js` which requires `fs_utils/source_file.js` which tries to reference `isNpmJSON` from `deppack` before `deppack` has been initialized in `config.js`.

### Environment

1. Brunch: 2.5.0
2. Node: 5.6.0
3. NPM: 3.7.1
4. Operating system: Windows 7 Business

### `package.json` contents

```json
{
  "name": "brunch-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {},
  "devDependencies": {
    "brunch": "2.5.0",
    "javascript-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0",
    "clean-css-brunch": "^2.0.0",
    "auto-reload-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```js
module.exports = {
  // See http://brunch.io for documentation.
  files: {
    javascripts: {joinTo: 'app.js'},
    stylesheets: {joinTo: 'app.css'},
    templates: {joinTo: 'app.js'}
  }
}
```

### Build output

```
  brunch:config Trying to load brunch-config +0ms
  brunch:plugins Loaded plugins: javascript-brunch, css-brunch, auto-reload-brunch +336ms
  brunch:watch add package.json +42ms
  brunch:watch add brunch-config.js +2ms
  brunch:watch add app\README.md +9ms
  brunch:list Reading app\README.md +2ms
  brunch:watch add app\initialize.js +2ms
  brunch:list Reading app\initialize.js +0ms
  brunch:file Init app\initialize.js: isntModule=false isWrapped=true +4ms
  brunch:pipeline Compiling app\initialize.js @ JavaScriptCompiler +4ms
  brunch:pipeline Compiling app\initialize.js @ AutoReloader +8ms
  brunch:list Reading node_modules\crypto-browserify\index.js +20ms
  brunch:modules Wrapping initialize.js @ commonjs +0ms
  brunch:list Compiled app\initialize.js +3ms
  brunch:file Init node_modules\crypto-browserify\index.js: isntModule=true isWrapped=true +1ms
  brunch:watch add app\assets\README.md +2ms
  brunch:asset Init app\assets\README.md directory=app\assets\ relativePath=README.md destinationPath=public\README.md +2ms
  brunch:watch add app\assets\index.html +2ms
  brunch:asset Init app\assets\index.html directory=app\assets\ relativePath=index.html destinationPath=public\index.html +1ms
  brunch:asset Copied app\assets\README.md +24ms
  brunch:asset Copied app\assets\index.html +2ms
  brunch:list Reading node_modules\randombytes\browser.js +44ms
  brunch:list Reading node_modules\create-hash\browser.js +2ms
  brunch:list Reading node_modules\create-hmac\browser.js +0ms
  brunch:list Reading node_modules\browserify-sign\algos.js +1ms
  brunch:list Reading node_modules\pbkdf2\browser.js +0ms
  brunch:list Reading node_modules\browserify-cipher\browser.js +1ms
  brunch:list Reading node_modules\diffie-hellman\browser.js +0ms
  brunch:list Reading node_modules\browserify-sign\browser.js +1ms
  brunch:list Reading node_modules\create-ecdh\browser.js +0ms
  brunch:list Reading node_modules\public-encrypt\browser.js +1ms
  brunch:modules Not wrapping (is vendor file) node_modules/crypto-browserify/index.js +0ms
  brunch:list Compiled node_modules\crypto-browserify\index.js +1ms
  brunch:file Init node_modules\create-hash\browser.js: isntModule=true isWrapped=true +1ms
  brunch:file Init node_modules\randombytes\browser.js: isntModule=true isWrapped=true +1ms
  brunch:file Init node_modules\pbkdf2\browser.js: isntModule=true isWrapped=true +1ms
  brunch:file Init node_modules\create-hmac\browser.js: isntModule=true isWrapped=true +1ms
  brunch:file Init node_modules\browserify-cipher\browser.js: isntModule=true isWrapped=true +0ms
  brunch:file Init node_modules\browserify-sign\browser.js: isntModule=true isWrapped=true +1ms
  brunch:file Init node_modules\browserify-sign\algos.js: isntModule=true isWrapped=true +1ms
  brunch:file Init node_modules\create-ecdh\browser.js: isntModule=true isWrapped=true +1ms
  brunch:file Init node_modules\public-encrypt\browser.js: isntModule=true isWrapped=true +0ms
  brunch:file Init node_modules\diffie-hellman\browser.js: isntModule=true isWrapped=true +1ms
  brunch:list Reading node_modules\buffer\index.js +68ms
  brunch:list Reading node_modules\process\browser.js +2ms
  brunch:modules Not wrapping (is vendor file) node_modules/randombytes/browser.js +0ms
  brunch:list Compiled node_modules\randombytes\browser.js +2ms
  brunch:list Reading node_modules\buffer\index.js +8ms
  brunch:modules Not wrapping (is vendor file) node_modules/browserify-sign/algos.js +1ms
  brunch:list Compiled node_modules\browserify-sign\algos.js +0ms
  brunch:file Init node_modules\process\browser.js: isntModule=true isWrapped=true +17ms
  brunch:file Init node_modules\buffer\index.js: isntModule=true isWrapped=true +1ms
  brunch:list Reading node_modules\public-encrypt\publicEncrypt.js +14ms
  brunch:list Reading node_modules\public-encrypt\privateDecrypt.js +1ms
  brunch:modules Not wrapping (is vendor file) node_modules/public-encrypt/browser.js +0ms
  brunch:list Compiled node_modules\public-encrypt\browser.js +1ms
  brunch:list Reading node_modules\diffie-hellman\lib\generatePrime.js +15ms
  brunch:list Reading node_modules\diffie-hellman\lib\primes.json +1ms
  brunch:list Reading node_modules\diffie-hellman\lib\dh.js +1ms
  brunch:modules Not wrapping (is vendor file) node_modules/diffie-hellman/browser.js +1ms
  brunch:list Compiled node_modules\diffie-hellman\browser.js +0ms
  brunch:file Init node_modules\public-encrypt\publicEncrypt.js: isntModule=true isWrapped=true +57ms
  brunch:file Init node_modules\public-encrypt\privateDecrypt.js: isntModule=true isWrapped=true +1ms
  brunch:file Init node_modules\diffie-hellman\lib\generatePrime.js: isntModule=true isWrapped=true +2ms
  brunch:file Init node_modules\diffie-hellman\lib\dh.js: isntModule=true isWrapped=true +0ms
D:\Projects\test-json\node_modules\brunch\lib\fs_utils\source_file.js:119
    const type = first && first.type || isNpmJSON(path) && 'javascript';
                                        ^

TypeError: isNpmJSON is not a function
  at new SourceFile (D:\Projects\test-json\node_modules\brunch\lib\fs_utils\source_file.js:119:41)
  at FileList._add (D:\Projects\test-json\node_modules\brunch\lib\fs_utils\file_list.js:164:18)
  at D:\Projects\test-json\node_modules\brunch\lib\fs_utils\file_list.js:191:18
  at D:\Projects\test-json\node_modules\fcache\index.js:21:5
  at tryToString (fs.js:414:3)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

### Reproduction

1. `md test-json`
2. `cd test-json`
3. `brunch new .`
4. `npm install -D brunch` (unless you have 2.5.0 installed globally I suppose)
5. Update `app/initialize.js` to add this line at the top: `var crypto = require('crypto');`
6. `brunch build`

**Comment by paulmillr** [comment]
that may be related to separating deppack to `gh:brunch/deppack`. @goshakkk could you take a look?

**Comment by goshakkk** [comment]
#1237 should fix that

**Comment by colinbate** [comment]
That's great. Thanks again guys.
