### ISSUE TITLE
BitBucket HTTPS URL fails with 'brunch new'

### ISSUE THREAD

**Issue by tgolden-andplus** [brunch/brunch#1265]
### Description

As of Brunch 2.5.3, I can't use a BitBucket HTTPS url anymore as an argument to `--skeleton`. It's unclear at what layer the error lies:

1. With brunch
2. With init-skeleton
3. With normalize-git-url

Here is the stacktrace I get, given the following command:

    brunch new https-test -s https://bitbucket.org/my-org/my-repo.git

```
url.js:73
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url);
    ^

TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:73:11)
    at Object.urlParse [as parse] (url.js:67:5)
    at normalize (C:\Users\Tom\AppData\Roaming\npm\node_modules\brunch\node_modules\normalize-git-url\normalize-git-url.js:4:20)
    at cleanURL (C:\Users\Tom\AppData\Roaming\npm\node_modules\brunch\node_modules\init-skeleton\index.js:109:10)
    at clone (C:\Users\Tom\AppData\Roaming\npm\node_modules\brunch\node_modules\init-skeleton\index.js:126:13)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\brunch\node_modules\init-skeleton\index.js:225:7
    at FSReqWrap.cb [as oncomplete] (fs.js:216:19)
```

### Environment

1. Brunch: 2.5.3
2. Node: 5.9.0
3. NPM: 3.7.3
4. Operating system: Windows 8.1

### `package.json` contents
N/A
### brunch config contents
N/A

### Other useful files, when present (`bower.json` etc.)
N/A

**Comment by goshakkk** [comment]
Thanks for your report! The problem was with init-skeleton and should be fixed by https://github.com/brunch/init-skeleton/pull/15
