### ISSUE TITLE
Brunch build on Heroku hangs trying to install devDependencies

### ISSUE THREAD

**Issue by nicolashery** [brunch/brunch#1276]
### Description

I've set up `brunch build --production` in my `package.json`'s `postinstall` script, but Brunch seems to hang when deploying to Heroku (see Heroku remote output below).

It looks like it's trying to install missing `devDependencies` (since Heroku runs `npm install --production`), but those dev dependencies aren't needed for my build process.

The workaround was to move all `devDependencies` to `dependencies`.

Is there a way to disable this automatic npm install from Brunch?

### Environment

1. Brunch: `2.6.1`
2. Node: `4.4.2`
3. NPM: `2.15.3`
4. Operating system: Heroku

### `package.json` contents

```json
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "postinstall": "if [ \"$NODE_ENV\" = \"production\" ]; then npm run build:prod; fi",
    "lint": "eslint --ignore-path .gitignore .",
    "clean": "rm -rf static && rm -rf assets.json",
    "start": "if [ \"$NODE_ENV\" = \"production\" ]; then node app/start; else npm run start:dev; fi",
    "start:dev": "source .env && concurrently --kill-others --raw 'brunch watch' 'browser-refresh app/start'",
    "build:prod": "brunch build --production"
  },
  "devDependencies": {
    "browser-refresh": "1.4.10",
    "concurrently": "2.0.0",
    "eslint": "2.5.3"
  },
  "dependencies": {
    "bootstrap": "3.3.6",
    "browser-refresh-client": "1.1.4",
    "browser-refresh-taglib": "1.0.4",
    "brunch": "2.6.1",
    "clean-css-brunch": "2.0.0",
    "css-brunch": "2.6.1",
    "express": "4.13.4",
    "fingerprint-brunch": "git://github.com/nicolashery/fingerprint-brunch.git#8d2c7649cbad49c0734abfa68e0078dc91b6644c",
    "javascript-brunch": "2.0.0",
    "marko": "3.0.5",
    "morgan": "1.7.0",
    "node-fetch": "1.4.1",
    "nprogress": "0.2.0",
    "query-string": "4.1.0",
    "spf": "2.3.2",
    "tcomb": "3.0.0",
    "uglify-js-brunch": "2.0.1"
  },
  "engines": {
    "node": "4.x",
    "npm": "2.x"
  }
```

### brunch config contents

```javascript
exports.config = {
  // See http://brunch.io/#documentation for docs.
  files: {
    javascripts: {
      joinTo: {
        'js/app.js': /^(app\/static\/js)/,
        'js/vendor.js': /^(?!app\/static\/js)/
      }
    },

    stylesheets: {
      joinTo: {
        'css/app.css': /^(app\/static\/css)/,
        'css/vendor.css': /^(?!app\/static\/css)/
      }
    }
  },

  conventions: {
    // This option sets where we should place non-css and non-js assets in.
    // Files in this directory will be copied to `paths.public`.
    assets: /^(app\/static\/assets)/
  },

  paths: {
    // Dependencies and current project directories to watch
    watched: [
      'app/static'
    ],

    // Where to compile files to
    public: 'static'
  },

  // Configure your plugins
  plugins: {
    fingerprint: {
      manifest: './assets.json',
      srcBasePath: 'static/',
      destBasePath: 'static/'
    }
  },

  modules: {
    // Require (run) modules at the end of a bundle
    autoRequire: {
      'js/app.js': ['static/js/main.js']
    }
  },

  npm: {
    styles: {
      bootstrap: ['dist/css/bootstrap.css'],
      nprogress: ['nprogress.css']
    },
    globals: {spf: 'spf/dist/spf.js'}
  }
};
```

### Other useful files, when present (`bower.json` etc.)

Heroku remote output:

```
Counting objects: 241, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (201/201), done.
Writing objects: 100% (241/241), 25.98 KiB | 0 bytes/s, done.
Total 241 (delta 90), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  4.x
remote:        engines.npm (package.json):   2.x
remote:
remote:        Resolving node version 4.x via semver.io...
remote:        Downloading and installing node 4.4.2...
remote:        Resolving npm version 2.x via semver.io...
remote:        Downloading and installing npm 2.15.3 (replacing version 2.15.0)...
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote:
remote: -----> Building dependencies
remote:        Pruning any extraneous modules
remote:        Installing node modules (package.json)
remote:
remote:        > example-app@1.0.0 postinstall /tmp/build_f662fadc65bc9b9ee4cc29bf6e8cff71
remote:        > if [ "$NODE_ENV" = "production" ]; then npm run build:prod; fi
remote:
remote:
remote:        > example-app@1.0.0 build:prod /tmp/build_f662fadc65bc9b9ee4cc29bf6e8cff71
remote:        > brunch build --production
remote:
remote:        04 Apr 02:29:36 - info: Using outdated versions of browser-refresh, concurrently, eslint, trying to update to match package.json versions
remote:        04 Apr 02:29:36 - info: Installing npm packages...
remote:        04 Apr 02:29:39 - info: compiling
remote:        04 Apr 02:29:39 - info: compiled 6 files into 4 files in 4.1 sec
remote: Verifying deploy.........................................................................
```

**Comment by paulmillr** [comment]
Brunch doesn't support npm v2. Can you ensure this also happens with v3?

**Comment by nicolashery** [comment]
Ah I see. Unfortunately, it also seems to hang with `npm@3` (tried both `node@4` and `node@5`).

Heroku output with `devDependencies` (hangs):

```
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Using set buildpack heroku/nodejs
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  4.x
remote:        engines.npm (package.json):   3.x
remote:
remote:        Resolving node version 4.x via semver.io...
remote:        Downloading and installing node 4.4.2...
remote:        Resolving npm version 3.x via semver.io...
remote:        Downloading and installing npm 3.8.5 (replacing version 2.15.0)...
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote:
remote: -----> Building dependencies
remote:        Pruning any extraneous modules
remote:        Installing node modules (package.json)
remote:
remote:        > example-marvel-app@1.0.0 postinstall /tmp/build_f28f0ad786edab081941fdc887018aba
remote:        > if [ "$NODE_ENV" = "production" ]; then brunch build --production -d; fi
remote:
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:config Trying to load brunch-config
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:plugins Loaded plugins: clean-css-brunch, css-brunch, fingerprint-brunch, javascript-brunch, uglify-js-brunch
remote:        04 Apr 11:58:17 - info: Using outdated versions of browser-refresh, concurrently, eslint, trying to update to match package.json versions
remote:        04 Apr 11:58:17 - info: Installing npm packages...
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:watch add package.json
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:watch add brunch-config.js
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:watch add /tmp/build_f28f0ad786edab081941fdc887018aba/node_modules/bootstrap/dist/css/bootstrap.css
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:list Reading node_modules/bootstrap/dist/css/bootstrap.css
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:watch add /tmp/build_f28f0ad786edab081941fdc887018aba/node_modules/nprogress/nprogress.css
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:list Reading node_modules/nprogress/nprogress.css
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:watch add node_modules/spf/dist/spf.js
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:list Reading node_modules/spf/dist/spf.js
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:file Init node_modules/bootstrap/dist/css/bootstrap.css: isntModule=true isWrapped=false
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:pipeline Compiling node_modules/bootstrap/dist/css/bootstrap.css @ CSSCompiler
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:list Compiled node_modules/bootstrap/dist/css/bootstrap.css
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:file Init node_modules/nprogress/nprogress.css: isntModule=true isWrapped=false
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:pipeline Compiling node_modules/nprogress/nprogress.css @ CSSCompiler
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:list Compiled node_modules/nprogress/nprogress.css
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:file Init node_modules/spf/dist/spf.js: isntModule=true isWrapped=true
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:modules Not wrapping (is vendor file) node_modules/spf/dist/spf.js
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:list Compiled node_modules/spf/dist/spf.js
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:watch add app/static/css/main.css
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:list Reading app/static/css/main.css
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:watch add app/static/js/main.js
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:list Reading app/static/js/main.js
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:file Init app/static/css/main.css: isntModule=false isWrapped=false
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:pipeline Compiling app/static/css/main.css @ CSSCompiler
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:list Compiled app/static/css/main.css
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:file Init app/static/js/main.js: isntModule=false isWrapped=true
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:pipeline Compiling app/static/js/main.js @ JavaScriptCompiler
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:list Reading node_modules/nprogress/nprogress.js
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:modules Wrapping static/js/main.js @ commonjs
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:list Compiled app/static/js/main.js
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:file Init node_modules/nprogress/nprogress.js: isntModule=true isWrapped=true
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:modules Not wrapping (is vendor file) node_modules/nprogress/nprogress.js
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:list Compiled node_modules/nprogress/nprogress.js
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:write Writing 4/4 files
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:generate Concatenating [node_modules/nprogress/nprogress.js, node_modules/spf/dist/spf.js] => static/js/vendor.js
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:generate Concatenating [app/static/js/main.js] => static/js/app.js
remote:        Mon, 04 Apr 2016 11:58:17 GMT brunch:generate Concatenating [node_modules/bootstrap/dist/css/bootstrap.css, node_modules/nprogress/nprogress.css] => static/css/vendor.css
remote:        Mon, 04 Apr 2016 11:58:18 GMT brunch:generate Concatenating [app/static/css/main.css] => static/css/app.css
remote:        Mon, 04 Apr 2016 11:58:18 GMT brunch:generate Optimizing static/js/vendor.js @ UglifyJSOptimizer
remote:        Mon, 04 Apr 2016 11:58:19 GMT brunch:generate Optimizing static/js/app.js @ UglifyJSOptimizer
remote:        Mon, 04 Apr 2016 11:58:20 GMT brunch:generate Optimizing static/css/vendor.css @ CleanCSSMinifier
remote:        Mon, 04 Apr 2016 11:58:20 GMT brunch:generate Optimizing static/css/app.css @ CleanCSSMinifier
remote:        Mon, 04 Apr 2016 11:58:20 GMT brunch:common Writing static/js/vendor.js
remote:        Mon, 04 Apr 2016 11:58:20 GMT brunch:common Writing static/js/app.js
remote:        Mon, 04 Apr 2016 11:58:20 GMT brunch:common Writing static/css/vendor.css
remote:        Mon, 04 Apr 2016 11:58:20 GMT brunch:common Writing static/css/app.css
remote:        04 Apr 11:58:20 - info: compiled 6 files into 4 files in 4.3 sec
remote: Verifying deploy............................................................................................
```

Heroku output after workaround (moving `devDependencies` into `dependencies`):

```
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Using set buildpack heroku/nodejs
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  4.x
remote:        engines.npm (package.json):   3.x
remote:
remote:        Resolving node version 4.x via semver.io...
remote:        Downloading and installing node 4.4.2...
remote:        Resolving npm version 3.x via semver.io...
remote:        Downloading and installing npm 3.8.5 (replacing version 2.15.0)...
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote:
remote: -----> Building dependencies
remote:        Pruning any extraneous modules
remote:        Installing node modules (package.json)
remote:
remote:        > example-marvel-app@1.0.0 postinstall /tmp/build_e8958660e798d9749bdc1a9df6a5c782
remote:        > if [ "$NODE_ENV" = "production" ]; then brunch build --production -d; fi
remote:
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:config Trying to load brunch-config
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:plugins Loaded plugins: clean-css-brunch, css-brunch, fingerprint-brunch, javascript-brunch, uglify-js-brunch
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:watch add package.json
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:watch add brunch-config.js
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:watch add /tmp/build_e8958660e798d9749bdc1a9df6a5c782/node_modules/bootstrap/dist/css/bootstrap.css
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:list Reading node_modules/bootstrap/dist/css/bootstrap.css
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:watch add /tmp/build_e8958660e798d9749bdc1a9df6a5c782/node_modules/nprogress/nprogress.css
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:list Reading node_modules/nprogress/nprogress.css
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:watch add node_modules/spf/dist/spf.js
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:list Reading node_modules/spf/dist/spf.js
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:file Init node_modules/bootstrap/dist/css/bootstrap.css: isntModule=true isWrapped=false
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:pipeline Compiling node_modules/bootstrap/dist/css/bootstrap.css @ CSSCompiler
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:list Compiled node_modules/bootstrap/dist/css/bootstrap.css
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:file Init node_modules/nprogress/nprogress.css: isntModule=true isWrapped=false
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:pipeline Compiling node_modules/nprogress/nprogress.css @ CSSCompiler
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:list Compiled node_modules/nprogress/nprogress.css
remote:        Mon, 04 Apr 2016 12:01:17 GMT brunch:file Init node_modules/spf/dist/spf.js: isntModule=true isWrapped=true
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:modules Not wrapping (is vendor file) node_modules/spf/dist/spf.js
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:list Compiled node_modules/spf/dist/spf.js
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:watch add app/static/css/main.css
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:list Reading app/static/css/main.css
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:watch add app/static/js/main.js
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:list Reading app/static/js/main.js
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:file Init app/static/css/main.css: isntModule=false isWrapped=false
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:pipeline Compiling app/static/css/main.css @ CSSCompiler
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:list Compiled app/static/css/main.css
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:file Init app/static/js/main.js: isntModule=false isWrapped=true
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:pipeline Compiling app/static/js/main.js @ JavaScriptCompiler
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:list Reading node_modules/nprogress/nprogress.js
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:modules Wrapping static/js/main.js @ commonjs
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:list Compiled app/static/js/main.js
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:file Init node_modules/nprogress/nprogress.js: isntModule=true isWrapped=true
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:modules Not wrapping (is vendor file) node_modules/nprogress/nprogress.js
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:list Compiled node_modules/nprogress/nprogress.js
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:write Writing 4/4 files
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:generate Concatenating [node_modules/nprogress/nprogress.js, node_modules/spf/dist/spf.js] => static/js/vendor.js
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:generate Concatenating [app/static/js/main.js] => static/js/app.js
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:generate Concatenating [node_modules/bootstrap/dist/css/bootstrap.css, node_modules/nprogress/nprogress.css] => static/css/vendor.css
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:generate Concatenating [app/static/css/main.css] => static/css/app.css
remote:        Mon, 04 Apr 2016 12:01:18 GMT brunch:generate Optimizing static/js/vendor.js @ UglifyJSOptimizer
remote:        Mon, 04 Apr 2016 12:01:19 GMT brunch:generate Optimizing static/js/app.js @ UglifyJSOptimizer
remote:        Mon, 04 Apr 2016 12:01:19 GMT brunch:generate Optimizing static/css/vendor.css @ CleanCSSMinifier
remote:        Mon, 04 Apr 2016 12:01:19 GMT brunch:generate Optimizing static/css/app.css @ CleanCSSMinifier
remote:        Mon, 04 Apr 2016 12:01:19 GMT brunch:common Writing static/js/vendor.js
remote:        Mon, 04 Apr 2016 12:01:19 GMT brunch:common Writing static/js/app.js
remote:        Mon, 04 Apr 2016 12:01:19 GMT brunch:common Writing static/css/vendor.css
remote:        Mon, 04 Apr 2016 12:01:19 GMT brunch:common Writing static/css/app.css
remote:        04 Apr 12:01:19 - info: compiled 6 files into 4 files in 2.5 sec
remote:        example-marvel-app@1.0.0 /tmp/build_e8958660e798d9749bdc1a9df6a5c782
remote:        ├── bootstrap@3.3.6
remote:        ├─┬ browser-refresh@1.4.10
remote:        │ ├── async@0.9.2
remote:        │ ├── browser-request@0.3.3
remote:        │ ├─┬ browserify@9.0.8
[...]
remote:
remote:
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 23.3M
remote: -----> Launching...
remote:        Released v8
remote:        https://example-marvel-app.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy.... done.
```

**Comment by goshakkk** [comment]
@paulmillr has nothing to do with npm version... our current auto-npm functionality doesn't take `--production` passed to `b/w` into account.

@nicolashery thank you for the report. I will work on the fix for this one

**Comment by nicolashery** [comment]
@goshakkk Cheers. Let me know if I can help test the fix

**Comment by goshakkk** [comment]
@nicolashery https://github.com/brunch/brunch/pull/1279 should fix it

**Comment by nicolashery** [comment]
Thanks for the quick turnaround! Upgraded to `2.6.2` and worked great :)

**Comment by jontonsoup** [comment]
I was getting this hanging issue (turned out I wasn't using -p in my heroku deploy), but now I'm getting this issue

```
remote:        > brunch build —p
remote:
remote:        Brunch: Local install exists, but failed to load it. Continuing with global install: { [Error: ENOENT: no such
file or directory, uv_chdir] errno: -2, code: 'ENOENT', syscall: 'uv_chdir' }
remote:        /tmp/build_7ea52a772b846cdd7bfa305545f7e26b/node_modules/graceful-fs/polyfills.js:18
remote:        chdir.call(process, d)
remote:        ^
remote:
remote:        Error: ENOENT: no such file or directory, uv_chdir
remote:        at Error (native)
remote:        at process.chdir (/tmp/build_7ea52a772b846cdd7bfa305545f7e26b/node_modules/graceful-fs/polyfills.js:18:9)
remote:        at Promise.all.then.checkDeps.then.out.error.filter.setDefaultJobsCount.constructor.application.loadConfig.then
.then.cfg.then.initCompilation.initWatcher.chokidar.watch.on.on.absPath.on.compile.assetErrors.forEach.Promise.all.then.then.w
atch (/tmp/build_7ea52a772b846cdd7bfa305545f7e26b/node_modules/brunch/lib/watch.js:346:15)
remote:        at exports.new.start (/tmp/build_7ea52a772b846cdd7bfa305545f7e26b/node_modules/brunch/lib/index.js:44:10)

remote:        at Command.listener (/tmp/build_7ea52a772b846cdd7bfa305545f7e26b/node_modules/commander/index.js:301:8)
remote:        at emitTwo (events.js:100:13)
remote:        at Command.emit (events.js:185:7)
remote:        at Command.parseArgs (/tmp/build_7ea52a772b846cdd7bfa305545f7e26b/node_modules/commander/index.js:615:12)
remote:        at Command.parse (/tmp/build_7ea52a772b846cdd7bfa305545f7e26b/node_modules/commander/index.js:458:21)
remote:        at Object.keys.forEach.exports.run (/tmp/build_7ea52a772b846cdd7bfa305545f7e26b/node_modules/brunch/lib/command
s.js:89:11)
remote:        at loadBrunch (/tmp/build_7ea52a772b846cdd7bfa305545f7e26b/node_modules/brunch/bin/brunch:24:7)
remote:        at /tmp/build_7ea52a772b846cdd7bfa305545f7e26b/node_modules/brunch/bin/brunch:30:5
remote:        at LOOP (fs.js:1609:14)
remote:        at _combinedTickCallback (internal/process/next_tick.js:67:7)
remote:        at process._tickCallback (internal/process/next_tick.js:98:9)
```

Let me know if you want me to make a new issue with this information. I'm not sure if this is related or not.

**Comment by goshakkk** [comment]
Please do create a separate issue and make sure to share a small app that reproduces the issue. Also mention the brunch, node, npm versions you are using.

**Comment by jontonsoup** [comment]
@goshakkk rolling back my brunch version to 1.X solved the problem. I'm strapped for time at the moment, but when I get a chance will add the info.

**Comment by goshakkk** [comment]
@jontonsoup thanks 😄
