### ISSUE TITLE
Let's make awesome validation for the config!

### ISSUE THREAD

**Issue by lydell** [brunch/brunch#1294]
Update/TLDR:

- [x] This issue was originally about validating brunch-config.js. That’s done (in a general way that ensures that future config is validated too).
- [x] Then, I suggested better error handling of missing files and valid but bad config. That’s done. (Let’s improve things more as we find them.)
- [ ] What’s left to do is plugin config validation.

---

The last couple of days I've been migrating a legacy project to brunch, and it's been a very positive experince!

I've used brunch a bit a few years ago, so it wasn't entirely new to me, but I still bumped into a few problems along the way. Most of the time, the problems arose from a mistake I had made in brunch-config.js. Here are a few examples.

---

I had just finished installing some brunch plugins and making a few edits to brunch-config.js. I then ran `brunch b` to test it out. (Yes, my primary testing consists of running `brunch b` and inspecting the output in `public/`.  I don't bother opening the browser until it looks ok.) This is the result:

```
$ brunch b
13 Apr 06:06:33 - error: Initialization error - TypeError: stylesheets.map is not a function
  at /home/lydell/myproject/node_modules/deppack/lib/load-globs-styles.js:21:26
  at Array.map (native)
  at Object.keys.map.each.then (/home/lydell/myproject/node_modules/deppack/lib/load-globs-styles.js:15:42)
  at /home/lydell/myproject/node_modules/deppack/lib/deppack.js:71:19
```

That's not very helpful! Initially, I had no clue at all what was wrong. I didn't know if it was my fault, some plugin's fault or a bug in brunch. I then noticed the word "stylesheets" in the error message, and thought of `config.files.stylesheets`, but that was a red herring. I then realized that if `.map` is not a function, that probably means that brunch expects an array in my config, but I gave it something else. I started commenting out my most recent changes in brunch-config.js until the problem went away. Turned out this was the problem:

```js
npm: {
  styles: {
    'font-awesome': 'css/font-awesome.css',
  },
},
```

... which is supposed to be (note the added `[` and `]`):

```js
npm: {
  styles: {
    'font-awesome': ['css/font-awesome.css'],
  },
},
```

---

Similarly to the above, I Initially thought that `npm.static` could be used like this:

```js
static: {
  'font-awesome': ['fonts/font-awesome.woff']
},
```

That gave me this:

```
$ brunch b
/home/lydell/myproject/node_modules/deppack/lib/deppack.js:34
  const isPackage = path => isNodeModule(path) && (statics || []).indexOf(path) === -1;
                                                                  ^

TypeError: (statics || []).indexOf is not a function
  at Object.path [as isPackage] (/home/lydell/myproject/node_modules/deppack/lib/deppack.js:34:67)
  at Deppack.isNpm (/home/lydell/myproject/node_modules/deppack/lib/deppack.js:100:27)
  at FileList.isIgnored (/home/lydell/myproject/node_modules/brunch/lib/fs_utils/file_list.js:65:17)
  at FileList._change (/home/lydell/myproject/node_modules/brunch/lib/fs_utils/file_list.js:187:26)
  at emitMany (events.js:121:13)
  at FileList.emit (events.js:195:7)
  at BrunchWatcher.changeFileList (/home/lydell/myproject/node_modules/brunch/lib/watch.js:239:19)
  at BrunchWatcher.startCompilation (/home/lydell/myproject/node_modules/brunch/lib/watch.js:314:12)
  at FSWatcher.<anonymous> (/home/lydell/myproject/node_modules/brunch/lib/watch.js:177:14)
  at emitTwo (events.js:100:13)
  at FSWatcher.emit (events.js:185:7)
  at FSWatcher.<anonymous> (/home/lydell/myproject/node_modules/chokidar/index.js:171:15)
  at FSWatcher._emit (/home/lydell/myproject/node_modules/chokidar/index.js:212:5)
  at FSWatcher.NodeFsHandler._handleFile (/home/lydell/myproject/node_modules/chokidar/lib/nodefs-handler.js:275:10)
  at FSWatcher.<anonymous> (/home/lydell/myproject/node_modules/chokidar/lib/nodefs-handler.js:473:21)
  at FSReqWrap.oncomplete (fs.js:82:15)
```

---

Once, I thought that the "conventions" option was called "convention", and was frustrated when my config didn't make any difference. Then I finally found that pesky missing "s".

---

### Proposal

[eslint](http://eslint.org/) and [stylelint](http://stylelint.io/) both validate their config files in an awesome way. They warn about unrecognized (misspelled) options, and make sure that the options are of the correct type.

Here are a few eslint errors:

```
Definition for rule 'comma-dangel' was not found

Configuration for rule "comma-dangle" is invalid:
Value "always-multilin" must be an enum value.

Configuration for rule "comma-dangle" is invalid:
Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed 'true').
```

stylelint:

```
Error: Undefined rule "selector-no-ids"

>> Invalid Option: Invalid option value "always-single-lines" for rule "selector-list-comma-space-after"
```

I think we should follow their lead! It's definitely worth the extra code!

- Warn about unrecognized options.
- Error on invalid option values.

### Environment

1. Brunch: 2.6.5 (both globally and locally)
2. Node: 5.9.1
3. NPM: 3.7.3
4. Operating system: Ubuntu 15.10

**Comment by paulmillr** [comment]
Great idea!

**Comment by lydell** [comment]
The new validation is looking great! Good job! :)

I’ve got three pieces of feedback.

1. A possible bug
2. Plugin config validation?
3. Even more error message awesomeness :)

# A possible bug

I can’t get the unknown option warnings (with Levensthein suggestions) to work
though:

```bash
# Setup.
$ mkdir myproject && cd myproject
$ brunch -v
2.7.2

# Expected: Detect unknown option `baths`.
# Actual: No warnings.
$ echo 'module.exports = {files: {}, baths: {}}' >brunch-config.js
$ brunch b

```


# Plugin config validation?

I understand that this might be difficult, but it would be awesome if we could validate plugin config as well :)

1. Perhaps we should recommend plugins to use skemata, and update the boiler plate, as well as all plugins in the brunch organization?

2. Perhaps plugins could somehow tell brunch what key name they use in `config.plugins`? Hell, I wouldn’t even mind if this:

   ```js
   plugins: {
     'uglify-js-brunch': {
        compress: {
          drop_console: true,
        },
     },
   },
   ```


# Even more error message awesomeness :)

The following might be considered out of scope for this issue, but there’s still room for more error message awesomness for newbies :). You can follow along in the terminal session below. I’ve added proposals as comments before some commands. Here is a summary of what the proposals are about:

1. Slight tweaks to the new skemata error messages.
2. Better handling of missing files.
3. Better handling of files with syntax errors.

```bash
# Setup.
$ mkdir myproject && cd myproject
$ brunch -v
2.7.2

# Great error message! :)
$ brunch b
25 Apr 06:02:15 - error: The directory does not seem to be a Brunch project. Create brunch-config.js or run brunch from the correct directory. Cannot find module '/home/lydell/myproject/brunch-config'

# Proposal:
#
# 1. Remove stack trace.
# 2. Suggest a minimal valid brunch-config.js:
#
#    module.exports = {
#      files: { ... }
#    }
$ touch brunch-config.js
$ brunch b
25 Apr 06:02:57 - error: Failed to load brunch config - brunch-config.js must have "files" property
  at /home/lydell/myproject/node_modules/brunch/lib/config.js:620:29

# Proposal: Same as above.
$ echo 'module.exports = {}' >brunch-config.js
~/myproject
$ brunch b
25 Apr 06:04:31 - error: Failed to load brunch config - brunch-config.js must have "files" property
  at /home/lydell/myproject/node_modules/brunch/lib/config.js:620:29

# Proposal: Same error as below (expected object, got null).
$ echo 'module.exports = {files: null}' >brunch-config.js
$ brunch b
25 Apr 06:05:03 - error: Failed to load brunch config - brunch-config.js must have "files" property
  at /home/lydell/myproject/node_modules/brunch/lib/config.js:620:29

# Proposal:
#
# 1. Remove stack trace.
# 2. Use `require('util').format`: `got: array ([])` instead of `got: array ()`.
$ echo 'module.exports = {files: []}' >brunch-config.js
$ brunch b
25 Apr 06:05:44 - error: config.files: expected: object, got: array ()
25 Apr 06:05:44 - error: Initialization error - config is not valid
  at v.object.fmt.errors.forEach.fmt.warnings.forEach (/home/lydell/myproject/node_modules/brunch/lib/config.js:168:11)

# Proposal:
#
# 1. Remove stack trace.
# 2. Change error message. Tell the user that brunch is not useful without
#    plugins, and that plugins must be listed in package.json. Possibly recommend
#    javascript-brunch and css-brunch.
$ echo 'module.exports = {files: {}}' >brunch-config.js
$ brunch b
25 Apr 06:15:35 - error: Initialization error - You probably need to execute `npm install` to install brunch plugins. Error: Cannot find module '/home/lydell/myproject/package.json'
  at /home/lydell/myproject/node_modules/brunch/lib/config.js:563:23
  at v.object.fmt.errors.forEach.Object.keys.forEach.environments.forEach.Object.keys.map.exports.install.exports.replaceConfigSlashes.Object.keys.forEach.types.map.type.map.types.forEach.types.forEach.types.forEach.Object.keys.forEach.exports.setConfigDefaults.Object.keys.forEach.normalized.paths.possibleConfigFiles.readComponents.then.Promise (/home/lydell/myproject/node_modules/brunch/lib/config.js:554:10)
  at v.object.fmt.errors.forEach.Object.keys.forEach.environments.forEach.Object.keys.map.exports.install.exports.replaceConfigSlashes.Object.keys.forEach.types.map.type.map.types.forEach.types.forEach.types.forEach.Object.keys.forEach.exports.setConfigDefaults.Object.keys.forEach.normalized.paths.possibleConfigFiles.readComponents.then.Promise.all.then (/home/lydell/myproject/node_modules/brunch/lib/config.js:586:5)

# Proposal:
#
# 1. Remove stack trace.
# 2. Change the error message. Tell the user that package.json has invalid
#    syntax, and nothing else.
$ touch package.json
25 Apr 06:20:23 - error: Initialization error - You probably need to execute `npm install` to install brunch plugins. SyntaxError: /home/lydell/myproject/package.json: Unexpected end of input
  at /home/lydell/myproject/node_modules/brunch/lib/config.js:563:23
  at v.object.fmt.errors.forEach.Object.keys.forEach.environments.forEach.Object.keys.map.exports.install.exports.replaceConfigSlashes.Object.keys.forEach.types.map.type.map.types.forEach.types.forEach.types.forEach.Object.keys.forEach.exports.setConfigDefaults.Object.keys.forEach.normalized.paths.possibleConfigFiles.readComponents.then.Promise (/home/lydell/myproject/node_modules/brunch/lib/config.js:554:10)
  at v.object.fmt.errors.forEach.Object.keys.forEach.environments.forEach.Object.keys.map.exports.install.exports.replaceConfigSlashes.Object.keys.forEach.types.map.type.map.types.forEach.types.forEach.types.forEach.Object.keys.forEach.exports.setConfigDefaults.Object.keys.forEach.normalized.paths.possibleConfigFiles.readComponents.then.Promise.all.then (/home/lydell/myproject/node_modules/brunch/lib/config.js:586:5)

# Proposal: Don’t be silent. Ideally: Detect that nothing happened and suggest why.
$ echo '{}' >package.json
$ brunch b
$ ls
brunch-config.js  node_modules  package.json

# Proposal: Remove stack trace.
$ echo 'module.exports = {' >brunch-config.js
$ brunch b
25 Apr 06:26:13 - error: Failed to load brunch config - Unexpected token )
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:387:25)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (/home/lydell/myproject/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Promise.then.config (/home/lydell/myproject/node_modules/brunch/lib/config.js:608:18)
  at v.object.fmt.errors.forEach.Object.keys.forEach.environments.forEach.Object.keys.map.exports.install.exports.replaceConfigSlashes.Object.keys.forEach.types.map.type.map.types.forEach.types.forEach.types.forEach.Object.keys.forEach.exports.setConfigDefaults.Object.keys.forEach.normalized.paths.possibleConfigFiles.readComponents.then.Promise.then.obj.catch (/home/lydell/myproject/node_modules/brunch/lib/config.js:600:10)
  at Object.v.object.fmt.errors.forEach.Object.keys.forEach.environments.forEach.Object.keys.map.exports.install.exports.replaceConfigSlashes.Object.keys.forEach.types.map.type.map.types.forEach.types.forEach.types.forEach.Object.keys.forEach.exports.setConfigDefaults.Object.keys.forEach.normalized.paths.possibleConfigFiles.readComponents.then.Promise.then.exports.loadConfig.tryToLoad.then.then.config.then.then.config.then [as loadConfig] (/home/lydell/myproject/node_modules/brunch/lib/config.js:649:10)
  at new BrunchWatcher (/home/lydell/myproject/node_modules/brunch/lib/watch.js:100:17)
  at Promise.all.then.checkDeps.then.out.error.filter.setDefaultJobsCount.constructor.application.loadConfig.then.then.cfg.then.initCompilation.initWatcher.chokidar.watch.on.on.absPath.on.compile.assetErrors.forEach.Promise.all.then.then.watch (/home/lydell/myproject/node_modules/brunch/lib/watch.js:360:10)
  at exports.new.start (/home/lydell/myproject/node_modules/brunch/lib/index.js:44:10)
  at Command.listener (/home/lydell/myproject/node_modules/commander/index.js:301:8)
  at emitTwo (events.js:100:13)
  at Command.emit (events.js:185:7)
  at Command.parseArgs (/home/lydell/myproject/node_modules/commander/index.js:615:12)
  at Command.parse (/home/lydell/myproject/node_modules/commander/index.js:458:21)
  at Object.keys.forEach.exports.run (/home/lydell/myproject/node_modules/brunch/lib/commands.js:89:11)
  at loadBrunch (/home/lydell/myproject/node_modules/brunch/bin/brunch:24:7)
  at /home/lydell/myproject/node_modules/brunch/bin/brunch:39:7
  at FSReqWrap.oncomplete (fs.js:82:15)

# Great error message! Proposal:
#
# 1. Remove stack trace.
# 2. Use `require('util').format`: `got: string ('css/font-awesome.css')`
#    instead of `got: string (css/font-awesome.css)`.
$ echo 'module.exports = {files: {}, npm: {styles: {"font-awesome": "css/font-awesome.css"}}}' >brunch-config.js
$ brunch b
25 Apr 06:34:17 - error: config.npm.styles.font-awesome: expected: array, got: string (css/font-awesome.css) 
25 Apr 06:34:17 - error: Initialization error - config is not valid
  at v.object.fmt.errors.forEach.fmt.warnings.forEach (/home/lydell/myproject/node_modules/brunch/lib/config.js:168:11)
```

**Comment by goshakkk** [comment]
Regarding a possible bug, it was fixed already https://github.com/brunch/skemata/pull/1 — now waiting for @paulmillr to cut a skemata release.

---

As for plugin config validation, that is something that's definitely popped in my mind and that I've been looking for possibilities to implement. Actually, my initial iteration of the schema validation did include support of plugins declaring their own schemas:

<img width="352" alt="screen shot 2016-04-22 at 4 32 48 pm" src="https://cloud.githubusercontent.com/assets/315596/14776501/a4ec221c-0acf-11e6-8c86-63b17ed53332.png">


For the time being though, we have decided to postpone this due to several factors:

* skemata might not be very mature yet. Exposing an unstable API for plugins means we will have to support the current skemata API for a long time... and this is not, well, something we'd want. Better wait some time to see how skemata performs in brunch, find possible culprits and bugs and ways to use we didn't think of before... and then expose to plugins

* support of default values for plugins, as well as production env overrides would have required changing the point where we load the plugins, and this change is also something we'd want to postpone

All in all, the original goal was to add config validation to the core, iterate upon it, and then when we think we're reached some maturity, allow plugins to declare their schemas.

---

As the message improvements go, I totally agree these do make sense 😉 Will work on that

**Comment by lydell** [comment]
@goshakkk I agree on everything you said. Go for it! :+1: :)

**Comment by lydell** [comment]
Btw, regarding plugin config: My idea was to leave it up to each plugin to do it, in whatever way they feel like. Such as `require('skemata'). But perhaps it's better to an API to plugins, as in your screen shot above.

**Comment by goshakkk** [comment]
@lydell the idea was that plugins shouldn't depend on skemata directly, instead, Brunch will explicitly pass it. A few upsides I can see is that if there's some bug in skemata, a new Brunch comes out with bumped skemata version and plugins work as expected.

Leaving the validation entirely to the plugins doesn't seem very cool from where I stand. The idea is that the all the config schemas (core, plugins') are merged into one, which ultimately means less false-negatives like ("you have `a2`, did you mean `a1`" — when there are both a1 and a2 keys handled by two different plugins) which will happen if there are separate schemas that are not aware of each other.

I understand the current version of skemata might be slightly limiting... which is why we are not exposing it to plugins at the moment. It'll get better with time and at some point we could allow developers to write their own validators, too, etc.

**Comment by goshakkk** [comment]
@paulmillr I think we can close this now.
