### ISSUE TITLE
An Error blocks building step. But does not block Watch step.

### ISSUE THREAD

**Issue by guneysus** [brunch/brunch#1327]
### Description

Running with `watch` parameter gives some errors but generates my files. But running with `build` parameter does not work as expected.

### Expected behavior

I was only expecting the generating my public folder. Althougth `watch` parameter (also with `--production` generates succesfully.

### Actual behavior

See https://github.com/guneysus/experiments/commit/51a36691feb0d565454d3cca8880af3ee5ce639f or [experiments-51a3669.zip](https://github.com/guneysus/experiments/archive/51a36691feb0d565454d3cca8880af3ee5ce639f.zip)

Running with watch gave some errors but compile and bundles my javascripts and generates public folder.

```
> brunch watch --server

30 Apr 21:58:07 - warn: config.modules.babel: perhaps you meant wrapper
30 Apr 21:58:08 - info: application started on http://localhost:3333/
30 Apr 21:58:08 - error: watch package.json ENOSPC 
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
30 Apr 21:58:08 - error: watch brunch-config.coffee ENOSPC 
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
30 Apr 21:58:13 - error: watch app/assets ENOSPC 
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
30 Apr 21:58:13 - error: watch app/app.js ENOSPC 
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
30 Apr 21:58:13 - error: watch app/initialize.js ENOSPC 
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
30 Apr 21:58:13 - info: compiling
30 Apr 21:58:13 - error: watch app/assets/two-way ENOSPC 
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
30 Apr 21:58:13 - error: watch app/assets/favicon.ico ENOSPC 
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
30 Apr 21:58:13 - error: watch app/assets/index.html ENOSPC 
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
30 Apr 21:58:13 - error: watch app/assets/two-way/index.html ENOSPC 
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
30 Apr 21:58:13 - info: compiled 3 files into 2 files, copied 3 in 6.8 sec
```

**But running with only `build` fails and does not touch public folder**

```
> brunch build --production

30 Apr 21:59:51 - warn: config.modules.babel: perhaps you meant wrapper
30 Apr 21:59:52 - error: watch package.json ENOSPC 
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
30 Apr 21:59:52 - warn: Nothing to compile. Most likely you don't have any source files yet, in which case, go ahead and create some! Otherwise, you probably don't have any plugin handling your source files. (For plain javascript, that would be "javascript-brunch")

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "prod"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! your-app@0.0.1 prod: `brunch build --production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the your-app@0.0.1 prod script 'brunch build --production'.
npm ERR! This is most likely a problem with the your-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     brunch build --production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs your-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls your-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ahmed/workspace/repos/experiments/npm-debug.log

```

### Environment

1. Brunch: `2.7.4`
2. Node: `v4.4.3`
3. NPM: `2.15.1`
4. Operating system: `Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa`

### `package.json` contents

```json
{
  "name": "your-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.0.1",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "prod": "brunch build --production"
  },
  "dependencies": {},
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "babel-brunch": "~6.0.0",
    "babel-preset-es2015": "~6.3.13",
    "brunch": "^2.4.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```coffe
exports.config = 
  files: 
    javascripts:
      joinTo:
          'javascripts/vendor.js': /^(?!app)/
          'javascripts/app.js': /^app/
    stylesheets:
      joinTo:
        'stylesheets/app.css': /^(app|vendor)/
        'test/stylesheets/test.css': /^test/
      order:
        before: ['vendor/styles/normalize-1.0.1.css']
        after: ['vendor/styles/helpers.css']              

  modules:
    babel:
      presets: ['es2015']


  # Every setting is optional.
  plugins:
    autoReload:
      enabled:
        css: on
        js: on
        assets: off
      port: [1234, 2345, 3456]
      delay: 200 if require('os').platform() is 'win32'

```

### Other useful files, when present (log, `bower.json` etc.)

* Debug log for `LOGGY_STACKS=true brunch build --debug`

```
Sat, 30 Apr 2016 22:08:17 GMT brunch:config Trying to load brunch-config
30 Apr 22:08:17 - [33mwarn[39m: config.modules.babel: perhaps you meant wrapper
Sat, 30 Apr 2016 22:08:18 GMT brunch:plugins Loaded plugins: auto-reload-brunch, babel-brunch, css-brunch, javascript-brunch
30 Apr 22:08:18 - [31merror[39m: watch package.json ENOSPC 
[90m  at exports._errnoException (util.js:870:11)
  at FSWatcher.start (fs.js:1234:19)
  at Object.fs.watch (fs.js:1262:11)
  at createFsWatchInstance (/home/ahmed/workspace/repos/experiments/node_modules/brunch/node_modules/chokidar/lib/nodefs-handler.js:37:15)
  at setFsWatchListener (/home/ahmed/workspace/repos/experiments/node_modules/brunch/node_modules/chokidar/lib/nodefs-handler.js:74:15)
  at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ahmed/workspace/repos/experiments/node_modules/brunch/node_modules/chokidar/lib/nodefs-handler.js:228:14)
  at FSWatcher.NodeFsHandler._handleFile (/home/ahmed/workspace/repos/experiments/node_modules/brunch/node_modules/chokidar/lib/nodefs-handler.js:255:21)
  at FSWatcher.<anonymous> (/home/ahmed/workspace/repos/experiments/node_modules/brunch/node_modules/chokidar/lib/nodefs-handler.js:473:21)
  at FSReqWrap.oncomplete (fs.js:82:15)
[39m
30 Apr 22:08:18 - [33mwarn[39m: Nothing to compile. Most likely you don't have any source files yet, in which case, go ahead and create some! Otherwise, you probably don't have any plugin handling your source files. (For plain javascript, that would be "javascript-brunch")
```

```

**Comment by paulmillr** [comment]
@goshakkk

**Comment by goshakkk** [comment]
The `ENOSPC` error means there is no free space on your drive. I've just cloned the repo you provided and checked out to the commit you specified. Both `watch` and `build` worked properly:

```
experiments-iss1327(51a3669...)$ brunch b --production
04 May 10:44:52 - warn: config.modules.babel: perhaps you meant wrapper
04 May 10:44:53 - info: compiled 2 files into app.js, copied 3 in 1.9 sec
experiments-iss1327(51a3669...)$ brunch w -s
04 May 10:46:42 - warn: config.modules.babel: perhaps you meant wrapper
04 May 10:46:43 - info: application started on http://localhost:3333/
04 May 10:46:43 - info: compiled 3 files into 2 files, copied 3 in 2.4 sec
```

(Btw, totally unrelated, but the babel plugin config should go under `config.plugins.babel`, not `config.modules.babel` — in general, all plugin configs live at `config.plugins.xxx`. `modules` is only used for these — https://github.com/brunch/brunch/blob/master/docs/config.md#modules)

**Comment by goshakkk** [comment]
@guneysus ping?

**Comment by bigp** [comment]
Where in the world do you set this `LOGGY_STACKS=true` parameter?
