### ISSUE TITLE
Brunch crash after branch change -d

### ISSUE THREAD

**Issue by modipeluri** [brunch/brunch#1374]
### Description

When changing from one git branch to another Brunch crashes at "reloading watcher" state, with the following error:

### Expected behavior

While this is not a huge problem as brunch can always be restarted, it would of course be nicer if it didn't crash.

### Actual behavior

Below the error log.
23 May 13:00:55 - info: Reloading watcher...
/Users/p.hiltunen/development/cpm4/frontend/src/main/webapp/node_modules/readdirp/node_modules/graceful-fs/polyfills.js:18
  chdir.call(process, d)
        ^

TypeError: Bad argument.
  at TypeError (native)
  at process.chdir (/Users/p.hiltunen/development/cpm4/frontend/src/main/webapp/node_modules/readdirp/node_modules/graceful-fs/polyfills.js:18:9)
  at process.chdir (/Users/p.hiltunen/development/cpm4/frontend/src/main/webapp/node_modules/graceful-fs/polyfills.js:14:9)
  at module.exports.watch (/Users/p.hiltunen/development/cpm4/frontend/src/main/webapp/node_modules/brunch/lib/watch.js:706:13)
  at restart (/Users/p.hiltunen/development/cpm4/frontend/src/main/webapp/node_modules/brunch/lib/watch.js:372:16)
  at reWatch (/Users/p.hiltunen/development/cpm4/frontend/src/main/webapp/node_modules/brunch/lib/watch.js:380:16)
  at /Users/p.hiltunen/development/cpm4/frontend/src/main/webapp/node_modules/brunch/lib/watch.js:387:14
  at EventEmitter.<anonymous> (/Users/p.hiltunen/development/cpm4/frontend/src/main/webapp/node_modules/brunch/lib/watch.js:616:14)
  at emitTwo (events.js:100:13)
  at EventEmitter.emit (events.js:185:7)
  at EventEmitter.<anonymous> (/Users/p.hiltunen/development/cpm4/frontend/src/main/webapp/node_modules/chokidar/index.js:136:15)
  at EventEmitter.FSWatcher._emit (/Users/p.hiltunen/development/cpm4/frontend/src/main/webapp/node_modules/chokidar/index.js:152:5)
  at EventEmitter.<anonymous> (/Users/p.hiltunen/development/cpm4/frontend/src/main/webapp/node_modules/chokidar/lib/nodefs-handler.js:268:12)
  at /Users/p.hiltunen/development/cpm4/frontend/src/main/webapp/node_modules/chokidar/lib/nodefs-handler.js:176:13
  at Array.forEach (native)
  at StatWatcher.<anonymous> (/Users/p.hiltunen/development/cpm4/frontend/src/main/webapp/node_modules/chokidar/lib/nodefs-handler.js:175:31)
  at emitTwo (events.js:100:13)
  at StatWatcher.emit (events.js:185:7)
  at StatWatcher._handle.onchange (fs.js:1369:10)

### Environment

1. Brunch: 1.8.0
2. Node: 5.9.0
3. NPM: 3.8.2
4. Operating system: OS X El Capitan 10.11.4

### `package.json` contents
  "devDependencies": {
    "assetsmanager-brunch": "^1.8.1",
    "auto-reload-brunch": "^1.8.1",
    "autoprefixer": "5.1.0",
    "autoprefixer-brunch": "~1.8.4",
    "brunch": "1.8.0",
    "cheerio": "~0.19.0",
    "coffee-script-brunch": "~1.8.0",
    "css-brunch": "~1.7.0",
    "growl": "git+ssh://git@stash.company.de:7999/cpm/growl.git",
    "jade": "~0.33",
    "jade-angularjs-brunch": "~1.1.1",
    "javascript-brunch": "~1.8.0",
    "jshint": "^2.6.0",
    "jshint-stylish": "^1.0.0",
    "karma": "^0.12.31",
    "karma-mocha": "^0.1.10",
    "karma-phantomjs-launcher": "^0.1.4",
    "karma-sinon-chai": "^0.3.0",
    "load-grunt-tasks": "~1.0.0",
    "mocha": "^2.1.0",
    "ng-annotate-uglify-js-brunch": ">= 1.0 < 1.8",
    "node-dir": "~0.1.8",
    "postcss-brunch": "~0.5.0",
    "sass-brunch": "git+ssh://git@stash.company.de:7999/pp/sass-brunch.git",
    "typescript-brunch": "git+ssh://git@stash.company.de:7999/cpm/typescript-brunch.git",
    "celonis-pdf-exporter": "git+ssh://git@stash.company.de:7999/cpm/cpm4-electron.git",
    "uglify-js-brunch": "~1.7.7"
  },
  "engines": {
    "node": ">=0.8.0"
  },

### brunch config contents

exports.config =
    notifications: false
    conventions:
        ignored: /vendor.js|codemirror.css|colorpicker.css|((.*(\/|\\))[_].*\.scss)/
    modules:
        definition: false
        wrapper: false
    paths:
        'public': 'build'
        'watched': [ 'app', 'api', 'vendor', 'charts' ]
    files:
        javascripts:
            joinTo:
                'js/vendor.js': /^bower_components|^vendor/
                'js/api.js': /^api/
                'js/app.js': /^app/
                'js/charts.js': /^charts/
            order:
                before: [
                    'bower_components/jquery/dist/jquery.js',
                    'bower_components/angular/angular.js'
                ]
        stylesheets:
            joinTo: 'css/app.css'
        templates:
            joinTo:
                'js/dontUseMe' : /^app/ # dirty hack for Jade compiling.
    plugins:
        typescript:
            doSomething: true
        jade:
            pretty: yes # Adds pretty-indentation whitespaces to output (false by default)
        jade_angular:
            locals: {}
            static_mask: /index.jade|welcome.jade|password.jade|portal.jade|link.jade/
        uglify:
            mangle: true
            compress:
                global_defs:
                    DEBUG: false
        autoReload:
            delay: 1000
        sass:
            mode: 'native' # 'ruby' / 'native'
            options:
                includePaths: ['bower_components/cpm4-strap/dist/sass']
        static_jade:
            path: [ /^app\/welcome.jade$/ ]
            asset: "app/assets"
        assetsmanager:
            copyTo: 'fonts': [ 'bower_components/cpm4-strap/dist/fonts/*' ]
            minTimeSpanSeconds: 60
    minify: true
    watcher:
        usePolling: true
    fileListInterval: 2000

**Comment by paulmillr** [comment]
@goshakkk

**Comment by goshakkk** [comment]
Does it happen on newer Brunch version (`2.8.0` is the most recent)?

**Comment by goshakkk** [comment]
ping

**Comment by modipeluri** [comment]
2.8.0 is working fine. Unfortunately because of some dependencies we were not yet able to upgrade. We're probably going to roll out our own plugin for the required functionality and then upgrade, so this issue can be closed. Thanks!
