### ISSUE TITLE
Do not require inotify to build a project

### ISSUE THREAD

**Issue by michallepicki** [brunch/brunch#1390]
### Description

Not every environment supports filesystem watchers. I understand they are necessary for live reloading, but should not be needed to build a project.

### Expected behavior

When I run 'brunch build' on a system that does not support filesystem watchers, the project builds.

### Actual behavior

When I run 'brunch build' on a system that does not support filesystem watchers I get an error. (log below)

### Environment

1. Brunch: 2.1.3
2. Node: v5.11.1
3. NPM: 3.8.6
4. Operating system: **Bash on Ubuntu on Windows** (Windows 10 Insider Preview Build 14361)

### Other useful files, when present (log, `bower.json` etc.)

[Related 'Linux subsystem in Windows' 's issue](https://github.com/Microsoft/BashOnWindows/issues/396). Since this is in their backlog, Linux subsystem on Windows may not support inotify in the future.

```
$ brunch build
09 Jun 00:41:14 - error: { [Error: watch web/static EPERM]
  code: 'EPERM',
  errno: 'EPERM',
  syscall: 'watch web/static',
  filename: 'web/static' }
/home/michal/lol/node_modules/chokidar/lib/nodefs-handler.js:77
    return watcher.close.bind(watcher);
                  ^

TypeError: Cannot read property 'close' of undefined
  at setFsWatchListener (/home/michal/lol/node_modules/chokidar/lib/nodefs-handler.js:77:19)
  at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/michal/lol/node_modules/chokidar/lib/nodefs-handler.js:228:14)
  at FSWatcher.NodeFsHandler._handleDir (/home/michal/lol/node_modules/chokidar/lib/nodefs-handler.js:407:19)
  at FSWatcher.<anonymous> (/home/michal/lol/node_modules/chokidar/lib/nodefs-handler.js:455:19)
  at FSWatcher.<anonymous> (/home/michal/lol/node_modules/chokidar/lib/nodefs-handler.js:460:16)
  at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by es128** [comment]
You might be able to resolve this just by setting `watcher: {usePolling: true}` in your brunch config.

**Comment by michallepicki** [comment]
This indeed resolved the issue. Thank you.
