### ISSUE TITLE
Brunch config must have "files" property

### ISSUE THREAD

**Issue by gts2257** [brunch/brunch#1397]
### Description

Brunch build fails in newly created project

### Expected behavior

I am trying to use brunch for the first time and I guess the expected behavior is to build project

### Actual behavior

running brunch build returns error
...\brunch-config.js. Error: Brunch config must have "files" property

### Environment

1. Brunch: 1.8.5
2. Node: 0.12.7
3. NPM: 3.9.2
4. Operating system: Windows 7

### `package.json` contents

```json
{
  "name": "brunch-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {},
  "devDependencies": {
    "brunch": "^1",
    "javascript-brunch": "^1",
    "css-brunch": "^1",
    "uglify-js-brunch": "^1",
    "clean-css-brunch": "^1",
    "auto-reload-brunch": "^1"
  }
}
```

### brunch config contents

```javascript
module.exports = {
  files: {
    javascripts: {joinTo: 'app.js'},
    stylesheets: {joinTo: 'app.css'},
    templates: {joinTo: 'app.js'}
  }
}
```

### Other useful files, when present (log, `bower.json` etc.)

```batch
E:\projects\brunch-app\node_modules\brunch\lib\helpers.js:592
      throw new Error("couldn\'t load config " + fullPath + ". " + error);
            ^
Error: couldn't load config E:\projects\brunch-app\brunch-config.js. Error: Brunch config must have "files" property
  at Object.exports.loadConfig (E:\projects\brunch-app\node_modules\brunch\lib\helpers.js:592:13)
  at initialize (E:\projects\brunch-app\node_modules\brunch\lib\watch.js:461:18)
  at new BrunchWatcher (E:\projects\brunch-app\node_modules\brunch\lib\watch.js:650:5)
  at module.exports.watch (E:\projects\brunch-app\node_modules\brunch\lib\watch.js:716:10)
  at start (E:\projects\brunch-app\node_modules\brunch\lib\index.js:15:31)
  at Command.listener (E:\projects\brunch-app\node_modules\commander\index.js:289:8)
  at Command.emit (events.js:110:17)
  at Command.parseArgs (E:\projects\brunch-app\node_modules\commander\index.js:572:12)
  at Command.parse (E:\projects\brunch-app\node_modules\commander\index.js:438:21)
  at Object.exports.run (E:\projects\brunch-app\node_modules\brunch\lib\cli.js:63:11)
  at Object.<anonymous> (E:\projects\brunch-app\node_modules\brunch\bin\brunch:11:22)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

List of files/dirs
```
E:\projects\brunch-app\.gitignore
E:\projects\brunch-app\app
E:\projects\brunch-app\brunch-config.js
E:\projects\brunch-app\package.json
E:\projects\brunch-app\README.md
E:\projects\brunch-app\app\assets
E:\projects\brunch-app\app\initialize.js
E:\projects\brunch-app\app\README.md
E:\projects\brunch-app\app\assets\index.html
E:\projects\brunch-app\app\assets\README.md
```

npm list

``` 
brunch-app@0.1.0 E:\projects\brunch-app
+-- auto-reload-brunch@1.8.1
| `-- ws@0.8.1
|   +-- UNMET OPTIONAL DEPENDENCY bufferutil@1.2.x
|   +-- options@0.0.6
|   +-- ultron@1.0.2
|   `-- UNMET OPTIONAL DEPENDENCY utf-8-validate@1.2.x
+-- brunch@1.8.5
| +-- anymatch@1.3.0
| | +-- arrify@1.0.1
| | `-- micromatch@2.3.8
| |   +-- arr-diff@2.0.0
| |   | `-- arr-flatten@1.0.1
| |   +-- array-unique@0.2.1
| |   +-- braces@1.8.5
| |   | +-- expand-range@1.8.2
| |   | | `-- fill-range@2.2.3
| |   | |   +-- is-number@2.1.0
| |   | |   +-- isobject@2.1.0
| |   | |   | `-- isarray@1.0.0
| |   | |   +-- randomatic@1.1.5
| |   | |   `-- repeat-string@1.5.4
| |   | +-- preserve@0.2.0
| |   | `-- repeat-element@1.1.2
| |   +-- expand-brackets@0.1.5
| |   | `-- is-posix-bracket@0.1.1
| |   +-- extglob@0.3.2
| |   +-- filename-regex@2.0.0
| |   +-- is-extglob@1.0.0
| |   +-- is-glob@2.0.1
| |   +-- kind-of@3.0.3
| |   | `-- is-buffer@1.1.3
| |   +-- normalize-path@2.0.1
| |   +-- object.omit@2.0.0
| |   | +-- for-own@0.1.4
| |   | | `-- for-in@0.1.5
| |   | `-- is-extendable@0.1.1
| |   +-- parse-glob@3.0.4
| |   | +-- glob-base@0.3.0
| |   | | `-- glob-parent@2.0.0
| |   | `-- is-dotfile@1.0.2
| |   `-- regex-cache@0.4.3
| |     +-- is-equal-shallow@0.1.3
| |     `-- is-primitive@2.0.0
| +-- anysort@1.0.1
| +-- async-each@0.1.6
| +-- async-waterfall@0.1.5
| +-- chokidar@1.0.6
| | +-- UNMET OPTIONAL DEPENDENCY fsevents@^0.3.8
| | +-- glob-parent@1.3.0
| | | `-- is-glob@2.0.1
| | +-- is-binary-path@1.0.1
| | | `-- binary-extensions@1.4.1
| | +-- is-glob@1.1.3
| | +-- path-is-absolute@1.0.0
| | `-- readdirp@1.4.0
| |   +-- graceful-fs@4.1.4
| |   +-- minimatch@0.2.14
| |   | +-- lru-cache@2.7.3
| |   | `-- sigmund@1.0.1
| |   `-- readable-stream@1.0.34
| |     +-- core-util-is@1.0.2
| |     +-- inherits@2.0.1
| |     +-- isarray@0.0.1
| |     `-- string_decoder@0.10.31
| +-- coffee-script@1.9.3
| +-- commander@2.7.1
| | `-- graceful-readlink@1.0.1
| +-- commonjs-require-definition@0.2.2
| +-- debug@2.1.3
| | `-- ms@0.7.0
| +-- deppack@0.1.5
| | +-- browser-resolve@1.7.2
| | | `-- resolve@1.1.5
| | `-- detective@4.3.1
| |   +-- acorn@1.2.2
| |   `-- defined@1.0.0
| +-- fcache@0.1.1
| +-- init-skeleton@0.4.4
| | +-- ncp@2.0.0
| | `-- rimraf@2.3.4
| |   `-- glob@4.5.3
| |     +-- inflight@1.0.5
| |     | `-- wrappy@1.0.2
| |     +-- minimatch@2.0.10
| |     | `-- brace-expansion@1.1.4
| |     |   +-- balanced-match@0.4.1
| |     |   `-- concat-map@0.0.1
| |     `-- once@1.3.3
| +-- loggy@0.2.2
| | +-- ansi-color@0.2.1
| | +-- date-utils@1.2.21
| | `-- growl@1.8.1
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| +-- pushserve@0.1.6
| | +-- commander@2.0.0
| | +-- connect-slashes@0.0.11
| | `-- express@3.3.8
| |   +-- buffer-crc32@0.2.1
| |   +-- commander@1.2.0
| |   | `-- keypress@0.1.0
| |   +-- connect@2.8.8
| |   | +-- bytes@0.2.0
| |   | +-- formidable@1.0.14
| |   | +-- pause@0.0.1
| |   | +-- qs@0.6.5
| |   | `-- uid2@0.0.2
| |   +-- cookie@0.1.0
| |   +-- cookie-signature@1.0.1
| |   +-- fresh@0.2.0
| |   +-- methods@0.0.1
| |   +-- mkdirp@0.3.5
| |   +-- range-parser@0.0.4
| |   `-- send@0.1.4
| |     `-- mime@1.2.11
| +-- quickly-copy-file@0.1.0
| +-- read-components@0.6.1
| | `-- component-builder@0.10.1
| |   +-- batch@0.2.1
| |   +-- component-require@0.3.1
| |   +-- cp@0.1.1
| |   +-- mkdirp@0.3.4
| |   `-- string-to-js@0.0.1
| `-- source-map@0.3.0
|   `-- amdefine@1.0.0
+-- clean-css-brunch@1.8.0
| `-- clean-css@3.4.17
|   +-- commander@2.8.1
|   `-- source-map@0.4.4
+-- css-brunch@1.7.0
+-- javascript-brunch@1.8.0
| `-- esprima@2.7.2
`-- uglify-js-brunch@1.7.8
  `-- uglify-js@2.4.24
    +-- async@0.2.10
    +-- source-map@0.1.34
    +-- uglify-to-browserify@1.0.2
    `-- yargs@3.5.4
      +-- camelcase@1.2.1
      +-- decamelize@1.2.0
      +-- window-size@0.1.0
      `-- wordwrap@0.0.2


```

**Comment by goshakkk** [comment]
Brunch 1.x is old, we've gone a long way since.

Try the new 2.8 (requires node 4 or higher).

**Comment by gts2257** [comment]
Thanks for the quick response :)
Unfortunately I don't have the option to update node at least not for a while

is there any idea about what is wrong so I can try and solve it myself?

**Comment by goshakkk** [comment]
Probably the 1.8 config needs to be wrapped into `{config: ...}` as in:

```javascript
module.exports = { config: {
  // here you go
}};
```

**Comment by gts2257** [comment]
It worked! Thanks for helping with such outdated version! :smile:
