### ISSUE TITLE
brunch b -p error : property 'content' of null

### ISSUE THREAD

**Issue by thenewbii** [brunch/brunch#1478]
### Description

Hello,
I am new here, and new in dev, also i am french so sorry for my bad english.
I work on a project with brunch, and i have a problem with stylesheets/joinTo files.
I want to have 3 differents CSS output files, so I write the following thing in my brunch-config.coffee

```
    stylesheets:
      joinTo:
        'css/file1.css': [/^mysite\/less\/header\// ]
        'css/file2.css': [/^mysite\/less\/content\// ]
        'css/file3.css': [/^mysite\/less\/footer\// ]
```
But it doesn't work (see below)

### Expected behavior

Have 3 output css files

### Actual behavior

When i used **brunch b -p**, i get the following error : 

```
19 Aug 16:53:07 - error: Cannot read property 'content' of null
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
```
So i do **LOGGY_STACKS=true brunch b –p**

And I get this : 

```
/home/dev/myproject/node_modules/graceful-fs/polyfills.js:18
  chdir.call(process, d)
        ^

Error: ENOENT: no such file or directory, uv_chdir
  at Error (native)
  at process.chdir (/home/dev/myproject/node_modules/graceful-fs/polyfills.js:18:9)
  at Promise.all.then.setProp.constructor.application.loadConfig.then.then.initCompilation.initWatcher.chokidar.watch.on.on.absPath.on.compile.assetErrors.forEach.Promise.all.then.then.watch (/home/dev/myproject/node_modules/brunch/lib/watch.js:326:15)
  at exports.new.start (/home/dev/myproject/node_modules/brunch/lib/index.js:43:10)
  at Command.listener (/home/dev/myproject/node_modules/commander/index.js:301:8)
  at emitTwo (events.js:87:13)
  at Command.emit (events.js:172:7)
  at Command.parseArgs (/home/dev/myproject/node_modules/commander/index.js:615:12)
  at Command.parse (/home/dev/myproject/node_modules/commander/index.js:458:21)
  at Object.keys.forEach.exports.run (/home/dev/myproject/node_modules/brunch/lib/commands.js:86:11)
  at /home/dev/.nvm/versions/node/v4.2.2/lib/node_modules/brunch/bin/brunch:25:7
  at FSReqWrap.oncomplete (fs.js:82:15)
```

### Environment

1. Brunch: 2.4.2
2. Node: 4.2.2
3. NPM: 3.0.0
4. Operating system: Windows 7

### `package.json` contents

```
{
  "name": "tiiproject",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "brunch": "2.4.2",
    "css-brunch": "^1.7.0",
    "javascript-brunch": "^1.7.1",
    "uglify-js-brunch": "^1.7.8"
  },
  "dependencies": {
    "bless-brunch": "^1.6.1",
    "bootstrap-less": "^3.3.8",
    "extend": "^3.0.0",
    "fastclick": "^1.0.6",
    "font-awesome": "^4.5.0",
    "hammerjs": "^2.0.8",
    "inherits": "^2.0.1",
    "jquery": "^2.2.1",
    "jquery-hammerjs": "^2.0.0",
    "jquery-ui": "1.10.5",
    "less-brunch": "^1.8.1",
    "node-smushit": "^0.5.1",
    "swfobject": "^2.2.1"
  }
}
```

### brunch config contents

```
exports.config =
  paths:
    public: 'web'
    watched: [
      'mysite/less',
    ]
  npm:
    enabled: true,
  files:
    javascripts:
      joinTo:
        'js/layout.js': [
          /^mysite\/js\/layout\//,
          /^mysite\/js\/player\//
        ]
    stylesheets:
      joinTo:
        'css/file1.css': [/^mysite\/less\/header\// ]
        'css/file2.css': [/^mysite\/less\/content\// ]
        'css/file3.css': [/^mysite\/less\/footer\// ]
  plugins:
    imageoptimizer:
      smushit: true
      path: 'img'
    bless:
      compress: false
      cacheBuster: true
  watcher:
    usePolling: true

```

Thanks for your help

**Comment by shvaikalesh** [comment]
Hey @thenewbii, could you please update Brunch to 2.8.2 and try again?

**Comment by paulmillr** [comment]
Also please try `npm install github:brunch/brunch`.

**Comment by thenewbii** [comment]
@shvaikalesh, @paulmillr : Thank's for your help, I update Brunch to 2.8.2 and it work :)

I'm curious, do you know what was the reason of this problem ?

**Comment by thenewbii** [comment]
Hello,
Finally update BRUNCH to 2.8.2 not solve the problem.

After hours of research, the problem comes of the **bless-brunch** plugin.
This plugin requires that the output files are named **app.css**, so the solution I find is this : 

```
stylesheets:
      joinTo:
        'css/header/app.css': [/^mysite\/less\/header\// ]
        'css/content/app.css': [/^mysite\/less\/content\// ]
        'css/footer/app.css': [/^mysite\/less\/footer\// ]
```

By doing this it worked perfectly.

I'll send an email to the author of **bless-brunch** to see if a change is possible.

Thanks all for your help,
