### ISSUE TITLE
Consistent Build Error

### ISSUE THREAD

**Issue by bretonio** [brunch/brunch#1568]
### Description

Failure to build any and all Brunch skeletons using node 6.6.0. 

They do build with 6.5.0, although with the warning `warn: config.files.javascripts.defaultExtension: perhaps you meant defaultExtensions` ..

Which is why I am posting this for informational purposes. 

### Expected Behavior

`sudo npm i && bower install && brunch build` should succeed in running the app.

### Actual Behavior

What actually happens:

/home/bretonio/.nvm/versions/node/v6.6.0/lib/node_modules/brunch/lib/fs_utils/file_list.js:77
        return path.match(test);
                    ^

TypeError: Cannot assign to read only property 'lastIndex' of object '[object RegExp]'
  at RegExp.exec (native)
  at RegExp.[Symbol.match] (native)
  at String.match (native)
  at FileList.module.exports.FileList.isIgnored (/home/bretonio/.nvm/versions/node/v6.6.0/lib/node_modules/brunch/lib/fs_utils/file_list.js:77:21)
  at /home/bretonio/.nvm/versions/node/v6.6.0/lib/node_modules/brunch/lib/fs_utils/file_list.js:85:26
  at Array.some (native)
  at FileList.module.exports.FileList.isIgnored (/home/bretonio/.nvm/versions/node/v6.6.0/lib/node_modules/brunch/lib/fs_utils/file_list.js:83:21)
  at FileList.module.exports.FileList._change (/home/bretonio/.nvm/versions/node/v6.6.0/lib/node_modules/brunch/lib/fs_utils/file_list.js:209:20)
  at FileList._change (/home/bretonio/.nvm/versions/node/v6.6.0/lib/node_modules/brunch/lib/fs_utils/file_list.js:4:57)
  at emitMany (events.js:127:13)
  at FileList.emit (events.js:201:7)
  at changeFileList (/home/bretonio/.nvm/versions/node/v6.6.0/lib/node_modules/brunch/lib/watch.js:205:19)
  at /home/bretonio/.nvm/versions/node/v6.6.0/lib/node_modules/brunch/lib/watch.js:681:18
  at Array.forEach (native)
  at /home/bretonio/.nvm/versions/node/v6.6.0/lib/node_modules/brunch/lib/watch.js:678:25
  at /home/bretonio/.nvm/versions/node/v6.6.0/lib/node_modules/brunch/lib/watch.js:558:16
  at /home/bretonio/.nvm/versions/node/v6.6.0/lib/node_modules/brunch/lib/watch.js:189:12
  at /home/bretonio/.nvm/versions/node/v6.6.0/lib/node_modules/brunch/node_modules/async-each/index.js:24:44
  at /home/bretonio/.nvm/versions/node/v6.6.0/lib/node_modules/brunch/lib/watch.js:176:14
  at /home/bretonio/.nvm/versions/node/v6.6.0/lib/node_modules/brunch/lib/fs_utils/common.js:17:12
  at FSReqWrap.oncomplete (fs.js:123:15)

### Environment

1. Brunch version 1.8.5
2. Node: 6.6.0
3. NPM: 3.10.3
4. Operating system: Linux 4.8.8.2-ARCH (x86_64)

I am happy to get Brunch back up and running. I Font Awesome heart it.

**Comment by shvaikalesh** [comment]
Hey @bretonio, thanks for the report. Could you please update Brunch to `^2` and try again?

**Comment by shvaikalesh** [comment]
I suspect this happens because we deep freeze config with `g`lobal or `s`ticky regular expressions. I believe we should not freeze them, but instead warn if any of those flags are set.

**Comment by shvaikalesh** [comment]
Hello there, we've refactored `FileList` and #1586 should completely fix this.
