### ISSUE TITLE
Error: Compiling of app/somefile.scss failed

### ISSUE THREAD

**Issue by recs182** [brunch/brunch#1590]
### Description
I simple run `brunch build` and everything seems to compile right in the public folder but some errors appears in the prompt:
```
brunch build
15 Dec 13:20:52 - info: compiling
15 Dec 13:20:57 - info: compiling.
15 Dec 13:20:58 - error: Compiling of app/stylesheets/component-title-pages.scss failed.
15 Dec 13:20:58 - error: Compiling of app/stylesheets/module-newsletter.scss failed.
15 Dec 13:20:58 - error: Compiling of app/stylesheets/module-payments.scss failed.
15 Dec 13:20:58 - error: Compiling of app/stylesheets/module-spotlight.scss failed.
15 Dec 13:20:58 - error: Compiling of app/stylesheets/page-cadastro.scss failed.
15 Dec 13:20:58 - error: Compiling of app/stylesheets/page-cadastro_login.scss failed.
15 Dec 13:20:58 - error: Compiling of app/stylesheets/page-conta.scss failed.
15 Dec 13:20:58 - error: Compiling of app/stylesheets/page-list_filtros.scss failed.
15 Dec 13:20:58 - error: Compiling of app/stylesheets/page-sacola.scss failed.
15 Dec 13:20:58 - error: Compiling of app/stylesheets/page-produto-variacoes.scss failed.
15 Dec 13:20:58 - error: Compiling of app/stylesheets/plugin-notifications.scssfailed.
15 Dec 13:20:58 - error: Compiling of app/stylesheets/plugin-rzslider.scss failed.
15 Dec 13:20:58 - error: Compiling of app/adm/stylesheets/plugin-notifications.scss failed.
15 Dec 13:20:59 - info: compiled 197 files into 5 files, copied 245 in 12.9 sec
```
Looking the compiled files, the style of those files that filed are in, so why it's showing errors?

### Environment
1. Brunch: 2.9.1
2. Node: 6.9.1
3. NPM: 3.10.8
4. Operating system: Windows 10 x64

### `package.json` contents
```
"devDependencies": {
    "babel-brunch": "^6.0.6",
    "brunch": "^2.9.1",
    "clean-css-brunch": "^2.0.0",
    "html-pages-brunch": "^2.5.0",
    "javascript-brunch": "^2.0.0",
    "sass-brunch": "^2.7.0",
    "uglify-js-brunch": "^2.0.1"
  },
```

### brunch config contents

```
module.exports = {
	production: {
		optimize: true,
		sourceMaps: true,
		plugins: {
			autoReload: {
				enabled: false
			}
		}
	},
	files: {
		javascripts: {
			joinTo: {
				'vendor.js': /^(?!app\/)/,
				'app.js': /^app(\/|\\)(?!adm)/,
				'adm/adm.js': /^app(\/|\\)(?=adm)/
			}
		},
		stylesheets: {
			joinTo: {
				'app.css': /^app(\/|\\)(?!adm)/,
				'adm/adm.css': /^app(\/|\\)(?=adm)/
			}
		}
	},
	plugins: {
		sass: {
			precision: 8
		},
		htmlPages: {
			htmlMin: {
				caseSensitive: false,
				collapseBooleanAttributes: true,
				collapseInlineTagWhitespace: false,
				collapseWhitespace: true,
				conservativeCollapse: false,
				html5: true,
				includeAutoGeneratedTags: false,
				keepClosingSlash: false,
				minifyCSS: true,
				minifyJS: true,
				preserveLineBreaks: false,
				preventAttributesEscaping: false,
				processConditionalComments: true,
				removeAttributeQuotes: true,
				removeComments: true,
				removeEmptyAttributes: true,
				removeOptionalTags: true,
				removeScriptTypeAttributes: true,
				removeStyleLinkTypeAttributes: true,
				sortAttributes: true,
				sortClassName: true
			},
			destination(path) {
				return path.replace(/^app[\/\\](.*)\.html$/, "$1.html");
			},
			disabled: false,
			compileAssets: true,
			preserveFrontMatter: false,
			removeFrontMatter: false,
			forceRemoveFrontMatter: false,
			frontMatterSeparator: '---'
		},
		cleancss:{
			keepSpecialComments: 0,
			removeEmpty: true
		},
		uglify:{
			mangle: false
		}
	}
}
```

### loggy_stack=true

```
brunch build LOGGY_STACK=true
Brunch: Local install exists, but failed to load it. Continuing with global inst
all: { Error: ENOENT: no such file or directory, uv_chdir
  at Error (native)
  at process.chdir (C:\Users\IP-19\Desktop\store-angular\node_modules\graceful-f
s\polyfills.js:21:9)
  at watch (C:\Users\IP-19\Desktop\store-angular\node_modules\brunch\lib\watch.j
s:425:15)
  at start (C:\Users\IP-19\Desktop\store-angular\node_modules\brunch\lib\index.j
s:45:10)
  at Command.listener (C:\Users\IP-19\Desktop\store-angular\node_modules\command
er\index.js:301:8)
  at emitTwo (events.js:106:13)
  at Command.emit (events.js:191:7)
  at Command.parseArgs (C:\Users\IP-19\Desktop\store-angular\node_modules\comman
der\index.js:615:12)
  at Command.parse (C:\Users\IP-19\Desktop\store-angular\node_modules\commander\
index.js:458:21)
  at Object.exports.run (C:\Users\IP-19\Desktop\store-angular\node_modules\brunc
h\lib\cli.js:123:11)
  at loadBrunch (C:\Users\IP-19\AppData\Roaming\npm\node_modules\brunch\bin\brun
ch:65:37)
  at Object.<anonymous> (C:\Users\IP-19\AppData\Roaming\npm\node_modules\brunch\
bin\brunch:75:5)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3
 errno: -4058, code: 'ENOENT', syscall: 'uv_chdir' }
C:\Users\IP-19\Desktop\store-angular\node_modules\graceful-fs\polyfills.js:21
  chdir.call(process, d)
        ^

Error: ENOENT: no such file or directory, uv_chdir
  at Error (native)
  at process.chdir (C:\Users\IP-19\Desktop\store-angular\node_modules\graceful-f
s\polyfills.js:21:9)
  at process.chdir (C:\Users\IP-19\AppData\Roaming\npm\node_modules\brunch\node_
modules\graceful-fs\polyfills.js:21:9)
  at watch (C:\Users\IP-19\AppData\Roaming\npm\node_modules\brunch\lib\watch.js:
425:15)
  at start (C:\Users\IP-19\AppData\Roaming\npm\node_modules\brunch\lib\index.js:
45:10)
  at Command.listener (C:\Users\IP-19\AppData\Roaming\npm\node_modules\brunch\no
de_modules\commander\index.js:301:8)
  at emitTwo (events.js:106:13)
  at Command.emit (events.js:191:7)
  at Command.parseArgs (C:\Users\IP-19\AppData\Roaming\npm\node_modules\brunch\n
ode_modules\commander\index.js:615:12)
  at Command.parse (C:\Users\IP-19\AppData\Roaming\npm\node_modules\brunch\node_
modules\commander\index.js:458:21)
  at Object.exports.run (C:\Users\IP-19\AppData\Roaming\npm\node_modules\brunch\
lib\cli.js:123:11)
  at loadBrunch (C:\Users\IP-19\AppData\Roaming\npm\node_modules\brunch\bin\brun
ch:65:37)
  at loadGlobalBrunch (C:\Users\IP-19\AppData\Roaming\npm\node_modules\brunch\bi
n\brunch:69:3)
  at Object.<anonymous> (C:\Users\IP-19\AppData\Roaming\npm\node_modules\brunch\
bin\brunch:81:5)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3
```

I can't see what's causing those errors, .scss files have its syntax ok.
Any clue of what could be causing the problem?

**Comment by FaKeller** [comment]
I had a similar issue and could resolve it by upgrading to the latest version of all brunch-related dependencies. Try running `npm outdated` or `yarn outdated` to check if you really have the latest version of all dependencies.

I suppose my issue arose due to an incompatibility between the used version of `brunch` and `sass-brunch`.

**Comment by recs182** [comment]
It worked. Thank you @FaKeller !
