### ISSUE TITLE
Error: ENOENT: no such file or directory, uv_chdir when specifiy listening address

### ISSUE THREAD

**Issue by eromoe** [brunch/brunch#1674]
Hi,

`brunch watch --server` works fine

but can't specify the listening address by:
```
brunch watch --server 0.0.0.0:3333
brunch watch --server -n 0.0.0.0
brunch watch --server --network 0.0.0.0
```

All get:

```
/mnt/spacy/spacy-annotator/node_modules/graceful-fs/polyfills.js:21
  chdir.call(process, d)
        ^

Error: ENOENT: no such file or directory, uv_chdir
  at Error (native)
  at process.chdir (/mnt/spacy/spacy-annotator/node_modules/graceful-fs/polyfills.js:21:9)
  at watch (/mnt/spacy/spacy-annotator/node_modules/brunch/lib/watch.js:377:15)
  at start (/mnt/spacy/spacy-annotator/node_modules/brunch/lib/index.js:47:28)
  at Command.listener (/mnt/spacy/spacy-annotator/node_modules/commander/index.js:301:8)
  at emitTwo (events.js:106:13)
  at Command.emit (events.js:191:7)
  at Command.parseArgs (/mnt/spacy/spacy-annotator/node_modules/commander/index.js:615:12)
  at Command.parse (/mnt/spacy/spacy-annotator/node_modules/commander/index.js:458:21)
  at Object.exports.run (/mnt/spacy/spacy-annotator/node_modules/brunch/lib/cli.js:109:11)
  at Object.<anonymous> (/mnt/spacy/spacy-annotator/node_modules/brunch/lib/run-cli.js:3:18)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

```

ENV:
OS: ubuntu 14.04 in docker
node: v6.9.5
npm: 3.10.10
brunch: 2.10.8

**Comment by paulmillr** [comment]
`network` option does not have an argument. it's just `brunch watch -s -n`.

**Comment by fischimglas** [comment]
i have the same issue since updated to npm 5.6. 
i could only solve it by downgrading to npm 5.01
