### ISSUE TITLE
Production build fails with "error: "version" is a required argument."

### ISSUE THREAD

**Issue by urosgruber** [brunch/brunch#1679]
### Description

building for production fails

### Expected behavior

building for production should finish

### Actual behavior

After runing production build I get 

```
18:30:29 - error: "version" is a required argument.
  at Object.getArg (/Users/uros/Sites/wandera/node_modules/source-map/lib/util.js:24:11)
  at SourceMapConsumer.BasicSourceMapConsumer (/Users/uros/Sites/wandera/node_modules/source-map/lib/source-map-consumer.js:288:22)
  at new SourceMapConsumer (/Users/uros/Sites/wandera/node_modules/source-map/lib/source-map-consumer.js:22:7)
  at prepareSourceMap (/Users/uros/Sites/wandera/node_modules/brunch/lib/fs_utils/generate.js:130:48)
  at processJob.then.optimized (/Users/uros/Sites/wandera/node_modules/brunch/lib/fs_utils/generate.js:151:17)
  at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Environment

1. Brunch: 2.10.8
1. Node.js: v6.7.0
1. NPM: 3.10.3
1. Operating system: osx

### `package.json` contents

```json
"devDependencies": {
    "autoprefixer": "^6.7.3",
    "brunch": "^2",
    "coffee-script-brunch": "^2",
    "coffeelint-brunch": "^2",
    "digest-brunch": "^1.4.0",
    "git-revision": "*",
    "groundskeeper-brunch": "0.0.4",
    "handlebars-brunch": "^2",
    "karma": "~0.13",
    "karma-chrome-launcher": "~0.1",
    "karma-coffee-preprocessor": "~0.2",
    "karma-coverage": "~1.1",
    "karma-firefox-launcher": "~0.1",
    "karma-junit-reporter": "~1.1",
    "karma-mocha": "~1.2",
    "karma-mocha-reporter": "~2.2",
    "karma-phantomjs-launcher": "~1.0",
    "karma-safari-launcher": "~0.1",
    "keyword-brunch": "^2",
    "mocha": "~3.1",
    "phantomjs-prebuilt": "~2.1",
    "postcss-brunch": "0.5",
    "sass-brunch": "^2",
    "uglify-js-brunch": "^2"
  },
```

### Other useful files, when present (log, `bower.json` etc.)

Latest version I used was 2.8.x and no errors with the same codebase and configuration

**Comment by denysdovhan** [comment]
Hi, @urosgruber!

I'm trying to help you with your problem. Could you help me and create a repo that reproduce your troubles with Brunch?

**Comment by urosgruber** [comment]
@denysdovhan could be a bit of a problem as code is closed source. I'll try and see if it's code related issue.

**Comment by paulmillr** [comment]
Make sure you're using latest postcss-brunch.

**Comment by urosgruber** [comment]
Ok. Found it. it's groundskeeper-brunch.

Here is my package.json

```json
{
  "author": "Foo",
  "name": "foo",
  "description": "",
  "version": "1.0.0",
  "private": true,
  "repository": {
    "type": "git",
    "url": ""
  },
  "engines": {
    "node": "0.8.x",
    "npm": "1.1.x"
  },
  "scripts": {
    "build": "brunch b",
    "build:prod": "brunch b -p"
  },
  "dependencies": {
    "backbone": "1.1.2"
  },
  "devDependencies": {
    "brunch": "^2",
    "groundskeeper-brunch": "0.0.4"
  },
  "license": "BSD"
}
```

and config.coffee

```coffee
exports.config =
    paths:
        public: 'public'
        watched: ['app/javascripts']

    fileListInterval: 300
    sourceMaps: true

    ## Files
    files:
        javascripts: 
            joinTo: 'app.js'

``` 

That is all you need. If groundskeeper-brunch is removed production build is fine as well. FYI non production works always.

**Comment by shvaikalesh** [comment]
Try https://babeljs.io/docs/plugins/transform-remove-console. `groundskeeper` is so 2013.

**Comment by denysdovhan** [comment]
@urosgruber [babel-brunch](https://github.com/babel/babel-brunch) with [`transform-remove-console`](https://babeljs.io/docs/plugins/transform-remove-console) plugin would be much more better solution:

```js
module.exports = {
  plugins: {
    babel: {
      plugins: ['transform-remove-console']
    }
  }
}
```
