### ISSUE TITLE
Brunch-Built module has local dependency issues when imported in another project

### ISSUE THREAD

**Issue by srodriki** [brunch/brunch#1686]
### Description

I'm working on a Vue plugin called [Animated Vue](https://npmjs.com/package/animated-vue) and I'm building my module with brunch. I've installed it into another project I had already working with brunch, and when I try to build it I get errors such as the following:

```shell
14:44:23 - error: Processing of node_modules/animated-vue/dist/animated-vue.js failed. Error: Could not load module './bounce' from '/Users/rjuliani/dev/wannaworkthere/application/node_modules/animated-vue/dist'. Make sure the file actually exists.
```

### Expected behavior

The build process completes successfully and does not have issues with animated-vue's internal dependencies.

### Actual behavior

I get an error where Brunch can't find a dependency that's internal to animated-vue, and is already inside dist/animated-vue.js

You can check out [animated-vue's](https://github.com/radical-dreamers/animated-vue) repo and my project can be found [here](https://github.com/radical-dreamers/wannaworkthere)

### Environment

1. Brunch: 2.10.8
1. Node.js: 6.9.5
1. NPM: 3.10.10
1. Operating system: MacOSX
1. Code editor: Atom

#### animated-vue
```json
{
  "name": "animated-vue",
  "version": "0.1.2",
  "description": "A set of transitions for Vue2 based on animate.css",
  "main": "dist/animated-vue.js",
  "scripts": {
    "build:dev": "brunch b",
    "build:production": "brunch b --production",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/radical-dreamers/animated-vue.git"
  },
  "keywords": [
    "Vue",
    "animate.css",
    "es6",
    "javascript",
    "Vue2",
    "transitions"
  ],
  "author": "Rodrigo Juliani <srodriki@gmail.com>",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/radical-dreamers/animated-vue/issues"
  },
  "homepage": "https://github.com/radical-dreamers/animated-vue#readme",
  "devDependencies": {
    "babel-brunch": "^6.0.6",
    "babel-eslint": "^7.1.1",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-es2016": "^6.22.0",
    "babel-preset-latest": "^6.22.0",
    "babel-preset-stage-3": "^6.22.0",
    "brunch": "^2.10.6",
    "eslint-brunch": "^3.12.0",
    "uglify-js-brunch": "^2.10.0",
    "vue-brunch": "^2.0.0"
  },
  "dependencies": {
    "vue": "^2.1.10",
    "animate.css": "^3.5.2"
  }
}
```

#### Project

```json
{
  "name": "wannaworkthere",
  "version": "1.0.1",
  "description": "UI for the wannaworkthere package",
  "main": "public/app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "brunch w --server",
    "build:local": "brunch b",
    "build:production": "PRODUCTION=true brunch b --production"
  },
  "repository": {
    "type": "git",
    "url": "git+https://gitlab.com/srodriki/wannaworkthere.git"
  },
  "keywords": [
    "vue",
    "brunch",
    "vuex",
    "vue-router"
  ],
  "author": "Rodrigo Juliani <srodriki@gmail.com>",
  "license": "MIT",
  "bugs": {
    "url": "https://gitlab.com/srodriki/wannaworkthere/issues"
  },
  "homepage": "https://gitlab.com/srodriki/wannaworkthere#README",
  "devDependencies": {
    "babel-brunch": "^6.0.6",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-es2016": "^6.22.0",
    "babel-preset-latest": "^6.22.0",
    "babel-preset-stage-3": "^6.22.0",
    "brunch": "^2.10.6",
    "copycat-brunch": "^1.1.0",
    "process-env-brunch": "^1.4.5",
    "sass-brunch": "^2.10.4",
    "vue-brunch": "^2.0.0"
  },
  "dependencies": {
    "animate.css": "^3.5.2",
    "animated-vue": "^0.1.2",
    "axios": "^0.15.3",
    "bulma": "^0.3.2",
    "font-awesome": "^4.7.0",
    "izitoast": "^1.1.1",
    "moment": "^2.17.1",
    "store": "^1.3.20",
    "vee-validate": "^2.0.0-beta.25",
    "vue": "^2.1.10",
    "vue-router": "^2.2.0",
    "vuex": "^2.1.2"
  }
}
```

#### animated-vue

```javascript

module.exports = {
  paths: {
    public: 'dist',
    watched: ['src']
  },
  files: {
    javascripts: {
      joinTo: 'animated-vue.js'
    },
    stylesheets: {
      joinTo: 'animated-vue.css'
    },
    templates: {
      joinTo: 'animated-vue.js'
    }
  },
  plugins: {
    babel: {
      presets: ['latest', 'stage-3']
    },
    vue: {
      extractCSS: false
    },
    eslint: {
      pattern: /^src\/.*\.js?$/,
      warnOnly: true
    },
    uglify: {
      mangle: false,
      compress: {
        global_defs: {
          DEBUG: false
        }
      }
    }
  },
  npm: {
    styles: {
      'animate.css': ['animate.css']
    }
  }
}

```

#### Project

```javascript
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'vendor.js': /^(?!app)/, // Files that are not in `app` dir.
        'app.js': /^app/
      }
    },
    stylesheets: {
      joinTo: 'app.css'/*{
        'vendor.css': /^(?!app)/,
        'app.js': /^app/
      }*/
    },
    templates: {
      joinTo: 'app.js'
    }
  },
  plugins: {
    babel: {
      presets: ['latest', 'stage-3']
    },
    vue: {
      extractCSS: false
    },
    sass: {
      mode: "native",
      precision: 8,
      options: {
        includePaths: [
          'node_modules/bulma'
        ]
      }
    },
    copycat: {
      'fonts': ['node_modules/font-awesome/fonts']
    }
  },
  npm: {
    styles: {
      'izitoast': ['dist/css/iziToast.css'],
      'font-awesome': ['css/font-awesome.css'],
      'animate.css': ['animate.css']
    }
  }
}

```

#### Brunch build stack

```shell
15:00:19 - error: Processing of node_modules/animated-vue/dist/animated-vue.js failed. Error: Could not load module './bounce' from '/Users/rjuliani/dev/wannaworkthere/application/node_modules/animated-vue/dist'. Make sure the file actually exists.
  at friendlyRequireError (/Users/rjuliani/dev/wannaworkthere/application/node_modules/deppack/lib/resolve.js:69:9)
  at err2 (/Users/rjuliani/dev/wannaworkthere/application/node_modules/deppack/lib/resolve.js:90:17)
  at /Users/rjuliani/dev/wannaworkthere/application/node_modules/browser-resolve/index.js:265:24
  at /Users/rjuliani/dev/wannaworkthere/application/node_modules/resolve/lib/async.js:55:18
  at load (/Users/rjuliani/dev/wannaworkthere/application/node_modules/resolve/lib/async.js:69:43)
  at onex (/Users/rjuliani/dev/wannaworkthere/application/node_modules/resolve/lib/async.js:92:31)
  at /Users/rjuliani/dev/wannaworkthere/application/node_modules/resolve/lib/async.js:22:47
  at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by shvaikalesh** [comment]
1. Consider not having `dist`. Sources are enough.
2. Brunch was not supposed to be used for building modules. CommonJS bundling is not state-of-the art right now. Will fix sometime later.

**Comment by srodriki** [comment]
@shvaikalesh 

Thanks for your answer. 

I was actually hoping to build my package as I wanted people not using ES6 to still be able to use it (i.e. just include it in a script tag from their html), very much like VueJS's library works.

So, if I were to leave it as src-only, am I right assuming the users would need to actually build the thing with other package builders as the only means to using this plugin?

**Comment by srodriki** [comment]
Also, if I do as you said, I get the following error: 

rocessing of node_modules/animated-vue/src/index.js failed. SyntaxError: 'import' and 'export' may only appear at the top level (5:4)

Which means brunch is somewhat not transpiling the code... for my module alone. Any ideas how to fix that?

**Comment by shvaikalesh** [comment]
There are a lot of people, myself included, that would prefer ES6 (because evergreen browsers/electron/phonegap) and `import`/`export` (because tree shaking). And those people would have to build it, yeah. We are trying to make it as easy as it can be with Brunch.

For `<script src=` use there are services like https://wzrd.in.

**Comment by srodriki** [comment]
@shvaikalesh I understand, and totally agree. I've opened another question, in which you also commented, because I'm having issues building that module as a dependency of another web app. Maybe you can help me sort it out?

Thanks a lot!
