### ISSUE TITLE
SyntaxError: Unexpected token when building ?

### ISSUE THREAD

**Issue by felix-d** [brunch/brunch#1707]
### Description

👋  I'm trying to compile a library and brunch outputs a build error, which does not happen with other build tools.

### Expected behavior

It should just works.

### Actual behavior

The library in question is [React relay network layer](https://github.com/nodkz/react-relay-network-layer/).

Here's the error I get

```
>  proj [master] ✗ LOGGY_STACKS=1 brunch build
18:36:50 - error: Processing of node_modules/react-relay-network-layer/lib/middleware/gqErrors.js failed. SyntaxError: Unexpected token (80:376)
  at Parser.pp$4.raise (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:2488:13)
  at Parser.pp.unexpected (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:623:8)
  at Parser.pp.semicolon (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:600:59)
  at Parser.pp$1.parseReturnStatement (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:894:55)
  at Parser.pp$1.parseStatement (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:744:32)
  at Parser.pp$1.parseBlock (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1040:23)
  at Parser.pp$3.parseFunctionBody (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:2362:22)
  at Parser.pp$1.parseFunction (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1132:8)
  at Parser.pp$1.parseFunctionStatement (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:868:15)
  at Parser.pp$1.parseStatement (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:739:17)
  at Parser.pp$1.parseBlock (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1040:23)
  at Parser.pp$3.parseFunctionBody (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:2362:22)
  at Parser.pp$1.parseFunction (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1132:8)
  at Parser.pp$3.parseExprAtom (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1999:17)
  at Parser.pp$3.parseExprSubscripts (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1872:19)
  at Parser.pp$3.parseMaybeUnary (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1849:17)
  at Parser.pp$3.parseExprOps (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1791:19)
  at Parser.pp$3.parseMaybeConditional (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1774:19)
  at Parser.pp$3.parseMaybeAssign (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1750:19)
  at Parser.pp$3.parseParenAndDistinguishExpression (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:2056:30)
  at Parser.pp$3.parseExprAtom (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1978:41)
  at Parser.pp$3.parseExprSubscripts (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1872:19)
  at Parser.pp$3.parseMaybeUnary (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1849:17)
  at Parser.pp$3.parseExprOps (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1791:19)
  at Parser.pp$3.parseMaybeConditional (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1774:19)
  at Parser.pp$3.parseMaybeAssign (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1750:19)
  at Parser.pp$3.parseExpression (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1722:19)
  at Parser.pp$1.parseStatement (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:777:45)
  at Parser.pp$1.parseBlock (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1040:23)
  at Parser.pp$3.parseFunctionBody (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:2362:22)
  at Parser.pp$1.parseFunction (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1132:8)
  at Parser.pp$3.parseExprAtom (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1999:17)
  at Parser.pp$3.parseExprSubscripts (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1872:19)
  at Parser.pp$3.parseMaybeUnary (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1849:17)
  at Parser.pp$3.parseExprOps (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1791:19)
  at Parser.pp$3.parseMaybeConditional (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1774:19)
  at Parser.pp$3.parseMaybeAssign (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1750:19)
  at Parser.pp$3.parseExprList (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:2418:20)
  at Parser.pp$3.parseSubscripts (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1900:29)
  at Parser.pp$3.parseExprSubscripts (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1875:21)
  at Parser.pp$3.parseMaybeUnary (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1849:17)
  at Parser.pp$3.parseExprOps (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1791:19)
  at Parser.pp$3.parseMaybeConditional (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1774:19)
  at Parser.pp$3.parseMaybeAssign (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1750:19)
  at Parser.pp$3.parseExpression (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:1722:19)
  at Parser.pp$1.parseStatement (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:777:45)
  at Parser.pp$1.parseTopLevel (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:672:23)
  at Parser.parse (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:529:15)
  at Object.parse (/Users/felixdescoteaux/petprojects/proj/node_modules/acorn/dist/acorn.js:3378:37)
  at parse (/Users/felixdescoteaux/petprojects/proj/node_modules/detective/index.js:9:18)
  at Function.exports.find (/Users/felixdescoteaux/petprojects/proj/node_modules/detective/index.js:44:15)
  at module.exports (/Users/felixdescoteaux/petprojects/proj/node_modules/detective/index.js:23:20)
  at /Users/felixdescoteaux/petprojects/proj/node_modules/deppack/lib/explore.js:61:43
  at sourceFile (/Users/felixdescoteaux/petprojects/proj/node_modules/deppack/lib/explore.js:104:18)

18:36:50 - info: compiled 17 files into 3 files, copied index.html in 1.3 sec
```

I have came across that problem on a larger project but have put together[ a minimal repo here](https://github.com/felix-d/brunch-error) using brunch and importing that library. The repo was generated with the brunch CLI.

### Environment

1. Brunch: *(make sure you're on the latest release!)*
1. Node.js: `v7.8.0`
1. NPM: *(npm v2 is not supported)*  `yarn v0.21.3`
1. Operating system: `OSX 10.12.4`
1. Code editor: vim

### `package.json` contents

```json
{
  "name": "brunch-app",
  "description": "Brunch.io application",
  "private": true,
  "author": "Brunch",
  "version": "0.0.1",
  "repository": "",
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {
    "react-relay-network-layer": "^2.0.1"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2",
    "babel-brunch": "~6.0",
    "babel-preset-latest": "^6",
    "brunch": "^2",
    "clean-css-brunch": "^2",
    "uglify-js-brunch": "^2"
  }
}
```

### brunch config contents

```javascript
// See http://brunch.io for documentation.
exports.files = {
  javascripts: {
    joinTo: {
      'vendor.js': /^(?!app)/, // Files that are not in `app` dir.
      'app.js': /^app/
    }
  },
  stylesheets: {joinTo: 'app.css'}
};

exports.plugins = {
  babel: {presets: ['latest']}
};
```
Related issue: https://github.com/nodkz/react-relay-network-layer/issues/45

**Comment by shvaikalesh** [comment]
Hey @felix-d, thanks for the issue.

The parser dies because Brunch replaces `process.env.NODE_ENV` in template string, but it should not. That sucks. Code is not a string. Sadly, I can't fix it immediately. Major update is coming (see #1664) that will solve this.

Have a nice day.

**Comment by shvaikalesh** [comment]
Quick fix: use fork with

```
process.env['NODE_ENV'] = ...
```

**Comment by felix-d** [comment]
Thanks @shvaikalesh I did something similar

**Comment by aMarCruz** [comment]
@felix-d , (jscc-brunch)[https://www.npmjs.com/package/jscc-brunch] is an alternative for conditional code inclusion.
It can read environment variables and exclude fragments based on them, and can be used in different file types.
