### ISSUE TITLE
error: Optimizing of public/app.js failed. L4712:6 SyntaxError: Unexpected token: name (CancelError)

### ISSUE THREAD

**Issue by yudao** [brunch/brunch#1715]
### Description

When I'm trying to build with --production flag i've got an error:
error: Optimizing of public/app.js failed. L4712:6 SyntaxError: Unexpected token: name (CancelError)

### Expected behavior

Compiling and optimizing in production mode

### Actual behavior

Optimizing doesn't work.
error: Optimizing of public/app.js failed. L4712:6 SyntaxError: Unexpected token: name (CancelError)

### Environment

1. Brunch: 2.4.0
1. Node.js: v4.3.2
1. NPM: 2.14.12
1. Operating system: macOS Sierra 10.12.6
1. Code editor: Atom 1.17.2 x64

### `package.json` contents

```json
{
  "name": "Botmimo",
  "description": "Description",
  "author": "Yudao",
  "version": "1.0.0",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "lint": "eslint app/**/*.js",
    "postinstall": "mkdir -p public/fonts && cp -R node_modules/font-awesome/fonts/* public/fonts && mkdir -p public/icons && cp -R node_modules/choices.js/assets/icons/* public/icons",
    "clean": "purifycss public/app.css public/index.js --info --rejected --out public/app-clear.css",
    "prod": "brunch build --production"
  },
  "dependencies": {
    "babel-polyfill": "^6.22.0",
    "bulma": "^0.4.0",
    "choices.js": "^2.7.8",
    "choo": "^5.2.0",
    "delay": "^2.0.0",
    "emojione_minimal": "^2.1.2",
    "gsap": "^1.19.1",
    "leaflet": "^1.0.3",
    "lodash": "^4.17.4",
    "nouislider": "^9.2.0",
    "numeral": "^2.0.6",
    "recastai-lib-browser": "^2.1.2",
    "slug": "^0.9.1",
    "superagent": "^3.5.2",
    "timeago.js": "^3.0.0"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "babel-brunch": "^6.0.0",
    "babel-eslint": "^7.1.1",
    "babel-plugin-lodash": "^3.2.11",
    "babel-preset-es2015": "^6.24.1",
    "brunch": "^2.4.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "eslint-brunch": "^3.12.0",
    "eslint-config-airbnb": "^14.0.0",
    "eslint-plugin-import": "^2.2.0",
    "font-awesome": "^4.7.0",
    "imageoptmizer-brunch": "0.0.6",
    "javascript-brunch": "^2.0.0",
    "jpegtran-bin": "^3.2.0",
    "keyword-brunch": "^2.0.0",
    "optipng-bin": "^3.1.2",
    "purify-css": "^1.1.9",
    "sass-brunch": "^2.9.0",
    "uglify-js-brunch": "^2.0.0"
  }
}

```

### brunch config contents

```javascript
module.exports = {
  files: {
    javascripts: { joinTo: 'app.js' },
    stylesheets: {
      joinTo: 'app.css'
    }
  },
  plugins: {
    babel: {
      plugins: ['lodash'],
      presets: ['es2015']
    },
    eslint: {
      pattern: /^app\/.*\.js?$/,
      warnOnly: true
    },
    keyword: {},
    uncss: {},
    sass: {
      mode: 'native',
      options: {
        includePaths: [
          'node_modules/bulma/sass',
          'node_modules/font-awesome/scss'
        ]
      }
    }
  },
  modules: {
    autoRequire: { 'app.js': ['initialize'] }
  },
  npm: {
    styles: {
      'animate.css': ['animate.css'],
      'leaflet': ['dist/leaflet.css'],
      'nouislider': ['distribute/nouislider.css'],
      }
  }
};
```

### Other useful files, when present (log, `bower.json` etc.)

npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/yudao/.nvm/versions/node/v4.3.2/bin/node',
1 verbose cli   '/Users/yudao/.nvm/versions/node/v4.3.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'prod' ]
2 info using npm@2.14.12
3 info using node@v4.3.2
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info preprod Botmimo@1.0.0
6 info prod Botmimo@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info Botmimo@1.0.0 Failed to exec prod script
9 verbose stack Error: Botmimo@1.0.0 prod: `brunch build --production`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/Users/yudao/.nvm/versions/node/v4.3.2/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/Users/yudao/.nvm/versions/node/v4.3.2/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid Botmimo@1.0.0
11 verbose cwd /Users/yudao/Documents/workspace/botmimo
12 error Darwin 16.7.0
13 error argv "/Users/yudao/.nvm/versions/node/v4.3.2/bin/node" "/Users/yudao/.nvm/versions/node/v4.3.2/bin/npm" "run" "prod"
14 error node v4.3.2
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error Botmimo@1.0.0 prod: `brunch build --production`
17 error Exit status 1
18 error Failed at the Botmimo@1.0.0 prod script 'brunch build --production'.
18 error This is most likely a problem with the Botmimo package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     brunch build --production
18 error You can get their info via:
18 error     npm owner ls Botmimo
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

**Comment by yudao** [comment]
It was the delay node package which caused this error.
Just removed it and add setTimeOut instead.
Sorry for disturbing :)

Thx.

Yu.
