### ISSUE TITLE
Brunch appears to be trying to build node_modules?

### ISSUE THREAD

**Issue by crummy** [brunch/brunch#1739]
### Description

1. `brunch new -s es6`
2. `npm install --save ol`
3. Edit `app/initialize.js`:
```
require('ol');
document.addEventListener('DOMContentLoaded', () => {
  // do your setup here
  console.log('Initialized app');
});
```
4. `brunch build`

### Expected behavior
```
> brunch build
18:26:46 - error: Processing of node_modules/ol/index.js failed. SyntaxError: 'import' and 'export' may only appear at the top level (253:0)
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace.
18:26:46 - info: compiled 2 files into 2 files, copied index.html in 1.5 sec
```
### Actual behavior

I'm very new to JS so not totally sure but I think brunch is trying to compile files in node_modules but they aren't es6 so it's confused? Regardless - `brunch build` should not return an error here.

### Environment

1. Brunch: *(make sure you're on the latest release!)* `2.10.10`
1. Node.js: `v6.11.0`
1. NPM: *(npm v2 is not supported)* `5.3.0`
1. Operating system: OSX Sierra
1. Code editor: VS Code

### `package.json` contents

```
{
  "name": "brunch-app",
  "description": "Brunch.io application",
  "private": true,
  "author": "Brunch",
  "version": "0.0.1",
  "repository": "",
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {
    "ol": "^4.3.1"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2",
    "babel-brunch": "~6.0",
    "babel-preset-latest": "^6",
    "brunch": "^2",
    "clean-css-brunch": "^2",
    "uglify-js-brunch": "^2"
  }
}

```

### brunch config contents

```
// See http://brunch.io for documentation.
exports.files = {
  javascripts: {
    joinTo: {
      'vendor.js': /^(?!app)/, // Files that are not in `app` dir.
      'app.js': /^app/
    }
  },
  stylesheets: {joinTo: 'app.css'}
};

exports.plugins = {
  babel: {presets: ['latest']}
};
```

### Other useful files, when present (log, `bower.json` etc.)

```
> brunch build -d
  brunch:config Trying to load brunch-config +0ms
  brunch:plugins Loaded plugins: auto-reload-brunch, babel-brunch +370ms
  brunch:watch add package.json +16ms
  brunch:watch add brunch-config.js +1ms
  brunch:watch add app/initialize.js +2ms
  brunch:list Reading app/initialize.js +1ms
  brunch:watch add app/styles.css +0ms
  brunch:list Reading app/styles.css +0ms
  brunch:file Init file app/initialize.js +2ms
  brunch:pipeline Compiling app/initialize.js @ auto-reload-brunch +3ms
  brunch:pipeline Compiling app/initialize.js @ babel-brunch +1ms
  brunch:file Init file app/styles.css +128ms
  brunch:list Compiled app/styles.css +1ms
  brunch:watch add app/assets/index.html +1ms
  brunch:list Reading app/assets/index.html +0ms
  brunch:asset Init asset app/assets/index.html +3ms
  brunch:list Compiled app/assets/index.html +0ms
  brunch:list Reading node_modules/ol/index.js +8ms
  brunch:list Compiled app/initialize.js +1ms
  brunch:file Init file node_modules/ol/index.js +0ms
  brunch:list Compiled node_modules/ol/index.js +13ms
18:33:00 - error: Processing of node_modules/ol/index.js failed. SyntaxError: 'import' and 'export' may only appear at the top level (253:0)
    at Parser.pp$4.raise (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:2488:13)
    at Parser.pp$1.parseStatement (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:760:14)
    at Parser.pp$1.parseBlock (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1040:23)
    at Parser.pp$3.parseFunctionBody (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:2362:22)
    at Parser.pp$1.parseFunction (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1132:8)
    at Parser.pp$3.parseExprAtom (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1999:17)
    at Parser.pp$3.parseExprSubscripts (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1872:19)
    at Parser.pp$3.parseMaybeUnary (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1849:17)
    at Parser.pp$3.parseExprOps (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1791:19)
    at Parser.pp$3.parseMaybeConditional (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1774:19)
    at Parser.pp$3.parseMaybeAssign (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1750:19)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:2056:30)
    at Parser.pp$3.parseExprAtom (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1978:41)
    at Parser.pp$3.parseExprSubscripts (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1872:19)
    at Parser.pp$3.parseMaybeUnary (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1849:17)
    at Parser.pp$3.parseExprOps (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1791:19)
    at Parser.pp$3.parseMaybeConditional (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1774:19)
    at Parser.pp$3.parseMaybeAssign (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1750:19)
    at Parser.pp$3.parseExpression (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1722:19)
    at Parser.pp$1.parseStatement (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:777:45)
    at Parser.pp$1.parseBlock (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1040:23)
    at Parser.pp$3.parseFunctionBody (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:2362:22)
    at Parser.pp$1.parseFunction (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1132:8)
    at Parser.pp$3.parseExprAtom (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1999:17)
    at Parser.pp$3.parseExprSubscripts (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1872:19)
    at Parser.pp$3.parseMaybeUnary (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1849:17)
    at Parser.pp$3.parseExprOps (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1791:19)
    at Parser.pp$3.parseMaybeConditional (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1774:19)
    at Parser.pp$3.parseMaybeAssign (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1750:19)
    at Parser.pp$3.parseExprList (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:2418:20)
    at Parser.pp$3.parseSubscripts (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1900:29)
    at Parser.pp$3.parseExprSubscripts (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1875:21)
    at Parser.pp$3.parseMaybeUnary (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1849:17)
    at Parser.pp$3.parseExprOps (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1791:19)
    at Parser.pp$3.parseMaybeConditional (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1774:19)
    at Parser.pp$3.parseMaybeAssign (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1750:19)
    at Parser.pp$3.parseExpression (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:1722:19)
    at Parser.pp$1.parseStatement (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:777:45)
    at Parser.pp$1.parseTopLevel (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:672:23)
    at Parser.parse (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:529:15)
    at Object.parse (/Users/crummy/code/brunch-test/node_modules/acorn/dist/acorn.js:3378:37)
    at parse (/Users/crummy/code/brunch-test/node_modules/detective/index.js:9:18)
    at Function.exports.find (/Users/crummy/code/brunch-test/node_modules/detective/index.js:44:15)
    at module.exports (/Users/crummy/code/brunch-test/node_modules/detective/index.js:23:20)
    at /Users/crummy/code/brunch-test/node_modules/deppack/lib/explore.js:61:43
    at sourceFile (/Users/crummy/code/brunch-test/node_modules/deppack/lib/explore.js:104:18)

  brunch:write Writing 2/2 files +83ms
  brunch:generate Concatenating [app/initialize.js] => public/app.js +4ms
  brunch:generate Concatenating [app/styles.css] => public/app.css +4ms
  brunch:generate Writing public/app.js +1ms
  brunch:generate Writing public/app.js.map +1ms
  brunch:generate Writing public/app.css +0ms
  brunch:generate Writing public/app.css.map +0ms
  brunch:write Writing 1/1 assets, removing 0 +2ms
  brunch:generate Writing public/index.html +0ms
18:33:00 - info: compiled 2 files into 2 files, copied index.html in 1.0 sec
```

**Comment by shvaikalesh** [comment]
Hello @crummy.

`import` and `export` may only appear at the top level.
More info on ES modules: http://2ality.com/2014/09/es6-modules-final.html

 It is a syntax error and it is produced when Brunch tries to extract dependencies from a file in `node_modules`. For Brunch to succeed, imported deps should be valid es5 or es6 code.

**Comment by crummy** [comment]
`ol` claims to be ES2015 which I think is ES6: https://www.npmjs.com/package/ol
Is this a bug on their end?

**Comment by shvaikalesh** [comment]
Oh, I am sorry. Seems like `babel-brunch` does not run. Please add

```js
exports.npm = {
  compilers: ['babel-brunch'],
};
```

to your config.

**Comment by crummy** [comment]
Thank you, that did it for me! `brunch build` works fine now.

**Comment by shvaikalesh** [comment]
That's great. If you wonder, we can't compile vendor deps with babel by default, because some popular libraries (handlebars, moment) have some tricky code that works in `<script>` context, but breaks in `<script type=module>`. For example, `this == window` on top level.

Indeed, we should improve `npm.compilers` (ideas here: https://github.com/brunch/brunch/issues/1582) and document it better. That is a WIP.
