### ISSUE TITLE
Brunch builds fail with ENOSPC if a text editor is having any file within the source tree open

### ISSUE THREAD

**Issue by almereyda** [brunch/brunch#1787]
### Description

Brunch runs into ENOSPC similarily to #1327 when doing `watch`, and is also affected in `build`s.

### Expected behavior

Brunch builds and watches the code also if the text editor is open.

### Actual behavior

This happens only when Sublime Text is running and is probably keeping open file handles?
Closing Sublime Text allows to run the build fine. This also happens if a file is opened and visible in Atom.
If the system is rebooted, the behaviour of `build` returns to normal, until calling `watch` again.

### Environment

1. Brunch: *2.10.12*
1. Node.js: 8.9.3
1. NPM: *5.6.0*
1. Operating system: Fedora 26
1. Code editor: Sublime Text / Atom

### `package.json` contents

https://github.com/TransforMap/transformap-editor/blob/staging/package.json

### brunch config contents

https://github.com/TransforMap/transformap-editor/blob/staging/brunch-config.js

### Other useful files, when present (log, `bower.json` etc.)

Clean:

```
ya@neocortex ~/https/github.com/TransforMap/transformap-editor (staging*) $ LOGGY_STACKS=true FQDN=transformap-data.apps.allmende.io npm run build -d
npm info it worked if it ends with ok                                    
npm info using npm@5.6.0            
npm info using node@v8.9.3          
npm info lifecycle transformap-editor@0.1.0~prebuild: transformap-editor@0.1.0
npm info lifecycle transformap-editor@0.1.0~build: transformap-editor@0.1.0

> transformap-editor@0.1.0 build /home/ya/https/github.com/TransforMap/transformap-editor
> brunch build --production         

15:07:05 - info: compiling          
15:07:05 - info: compiled 26 files into 4 files, copied 11 in 4.0 sec    
npm info lifecycle transformap-editor@0.1.0~postbuild: transformap-editor@0.1.0
```

Dirty:

```
<a@neocortex ~/https/github.com/TransforMap/transformap-editor (staging*) $ LOGGY_STACKS=true FQDN=transformap-data.apps.allmende.io npm run build -d
npm info it worked if it ends with ok      
npm info using npm@5.6.0                   
npm info using node@v8.9.3                 
npm info lifecycle transformap-editor@0.1.0~prebuild: transformap-editor@0.1.0         
npm info lifecycle transformap-editor@0.1.0~build: transformap-editor@0.1.0            

> transformap-editor@0.1.0 build /home/ya/https/github.com/TransforMap/transformap-editor
> brunch build --production                

15:08:08 - error: watch app ENOSPC         
    at _errnoException (util.js:1024:11)   
    at FSWatcher.start (fs.js:1374:19)     
    at Object.fs.watch (fs.js:1400:11)     
    at createFsWatchInstance (/home/ya/https/github.com/TransforMap/transformap-editor/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/ya/https/github.com/TransforMap/transformap-editor/node_modules/chokidar/lib/nodefs-handler.js:74:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ya/https/github.com/TransforMap/transformap-editor/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/ya/https/github.com/TransforMap/transformap-editor/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/ya/https/github.com/TransforMap/transformap-editor/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/ya/https/github.com/TransforMap/transformap-editor/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:153:5)  
                     
npm info lifecycle transformap-editor@0.1.0~build: Failed to exec build script         
npm ERR! code ELIFECYCLE                   
npm ERR! errno 1     
npm ERR! transformap-editor@0.1.0 build: `brunch build --production`                   
npm ERR! Exit status 1                     
npm ERR!             
npm ERR! Failed at the transformap-editor@0.1.0 build script.                          
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:                                   
npm ERR!     /home/ya/.npm/_logs/2018-01-22T14_08_08_889Z-debug.log                    
```

Please note installing the package warns for a package that is not installed for the Darwin platform, but relates to file system events. Maybe `chokidar` is choking here?

```
ya@neocortex ~/https/github.com/TransforMap/transformap-editor (staging*) $ npm i

> transformap-editor@0.1.0 postinstall /home/ya/https/github.com/TransforMap/transformap-editor
> ./scripts/postinstall

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 4.027s
```

**Comment by almereyda** [comment]
This seems to be an atomic write issue of the editors, and could be mentionned in the docs.

- https://parceljs.org/hmr.html#safe-write

**Comment by Fire-Dragon-DoL** [comment]
Hello! Facing the same issue, but I definitely would like to avoid disabling atomic writes. Any solution?
