### ISSUE TITLE
Update native-notifier dependency

### ISSUE THREAD

**Issue by paulmedynski** [brunch/brunch#1831]
### Description

The watcher terminates if the initial build doesn't succeed.  For example, if TypeScript compilation of a file fails, the watcher terminates.

### Expected behaviour

The watcher stays running and continues to try re-building as files change.

This is probably a feature request rather than a bug, per se.  My project only contains TypeScript files, so the issue may be harder to deal with for a heterogeneous build setup.

### Actual behaviour

See description.

### Environment

1. Brunch: 2.10.17
2. Node.js:  10.11.0
3. NPM: 6.4.1
4. Operating system:  Linux
5. Code editor:  Emacs

**Comment by paulmedynski** [comment]
Nothing public, but I can set something up when I get a change.  I opened this issue so I wouldn't forget.  It might be something I could take a stab at in the future.

I did notice that the watcher terminates if a recompile fails, so it isn't limited to the initial build.  It could be that typescript-brunch isn't reporting the error in a way that brunch can track against the source file and continue watching.  I haven't looked at the brunch code yet, so I'm just guessing here.

I think generally, though, that it should be possible (for some subset of build steps?) to have brunch tolerate a failure and continue watching, and just skip any subsequent steps that rely on the failed file.  That's probably an oversimplification, but it seems like it would be useful.

I'll post back here once I have a better idea of what's going on, and how to improve it.

**Comment by paulmedynski** [comment]
I tracked this down to the `notifications` option being enabled by default.  I don't have the necessary OS notification service installed on my Ubuntu machine, so `brunch` crashes like this whenever any files fail to lint/compile/whatever:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn notify-send ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I have two suggestions here:

1.  Change the `notifications` default to `false`.

2.  Have `brunch` check for the necessary OS notification service, and if not present, log something helpful.

Disabling `notifications` solves the problem, but it took a while to figure out.

**Comment by paulmedynski** [comment]
The master version of native-notify silently consumes spawn errors, and would keep the problem described in this issue from occurring.  Can we update brunch to use the latest native-notifier?

**Comment by paulmedynski** [comment]
Opened paulmillr/native-notifier#7 to get the native-notifier fixes released.
