### ISSUE TITLE
Unable to connect to git while creating a new brunch project

### ISSUE THREAD

**Issue by BrooksDuBoisAramark** [brunch/brunch#1847]
When running `brunch new` or any other skeleton command like `brunch new --skeleton brunch/with-es6` the project fails to be created.

The error message I see:

```

12:21:34 - log: Pulling recent changes from git repo "git://github.com/brunch/with-react.git" to "/Users/bdubois/.brunch/skeletons/eb762f15f138e281aa63304a2d216881b88d1332"...
12:21:47 - log: Could not pull, using cached version (Error: Command failed: git pull origin master
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Operation timed out

)
12:21:47 - log: Copying local skeleton to "/Users/bdubois/Documents/healthCareSetup/dir"...
(node:19646) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1090:7)
    at ncp (/Users/bdubois/.npm-global/lib/node_modules/brunch/node_modules/ncp/lib/ncp.js:16:26)
    at /Users/bdubois/.npm-global/lib/node_modules/brunch/node_modules/micro-promisify/index.js:8:14
    at new Promise (<anonymous>)
    at /Users/bdubois/.npm-global/lib/node_modules/brunch/node_modules/micro-promisify/index.js:6:10
    at mkdirp.then (/Users/bdubois/.npm-global/lib/node_modules/brunch/node_modules/init-skeleton/lib/index.js:76:12)
(node:19646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19646) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am on the latest npm and brunch versions, with a good network connection.  I am able to visit the repos and clone them manually with http and ssh.

**Comment by brooksdubois** [comment]
Never mind it looks like it works again, must have been a problem on my end (or with github).

**Comment by BrooksDuBoisAramark** [comment]
This seems to happen when I'm using a public network (like starbucks or something). I'm guessing it's not an issue with brunch.
