### ISSUE TITLE
Brunch 3.0.0 - Error: Cannot find module 'readable-stream/duplex'

### ISSUE THREAD

**Issue by Arcesilas** [brunch/brunch#1851]
### Description
A module seems to be missing

### Expected behavior
Brunch should load and build

### Actual behavior
Error happens when building

### Environment

1. Brunch: 3.0.0
1. Node.js: 12.13.1 (LTS)
1. NPM: 6.12.1
1. Operating system: Linux Fedora 31
1. Code editor: Atom

### `package.json` contents

```json
{
    "private": true,
    "devDependencies": {
        "brunch": "^3.0.0"
    }
}
```

### brunch config contents

```javascript
module.exports = {
  paths: {
    public: 'public/assets/',
    watched: ['resources/js', 'resources/sass']
  },
  files: {
    javascripts: {
      joinTo: {
        'javascripts/app.js': /^app/,
        'javascripts/vendor.js': /^(?!app)/
      }
    },
    stylesheets: {joinTo: 'app.css'},
  }
}
```

### Other useful files, when present (log, `bower.json` etc.)
```
Brunch: Local install exists, but failed to load it. Continuing with global install: Error: Cannot find module 'readable-stream/duplex'
Require stack:
- /path/to/project/node_modules/node-browser-modules/index.js
- /path/to/project/node_modules/deppack/lib/shims.js
- /path/to/project/node_modules/deppack/lib/modules.js
- /path/to/project/node_modules/deppack/lib/deppack.js
- /path/to/project/node_modules/deppack/index.js
- /path/to/project/node_modules/brunch/lib/fs_utils/write.js
- /path/to/project/node_modules/brunch/lib/watch.js
- /path/to/project/node_modules/brunch/lib/index.js
- /path/to/project/node_modules/brunch/lib/cli.js
- /path/to/project/node_modules/brunch/bin/brunch
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)
    at Object.<anonymous> (/path/to/project/node_modules/node-browser-modules/index.js:27:33)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/path/to/project/node_modules/deppack/lib/shims.js:3:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path/to/project/node_modules/node-browser-modules/index.js',
    '/path/to/project/node_modules/deppack/lib/shims.js',
    '/path/to/project/node_modules/deppack/lib/modules.js',
    '/path/to/project/node_modules/deppack/lib/deppack.js',
    '/path/to/project/node_modules/deppack/index.js',
    '/path/to/project/node_modules/brunch/lib/fs_utils/write.js',
    '/path/to/project/node_modules/brunch/lib/watch.js',
    '/path/to/project/node_modules/brunch/lib/index.js',
    '/path/to/project/node_modules/brunch/lib/cli.js',
    '/path/to/project/node_modules/brunch/bin/brunch'
  ]
}
Cannot find module 'readable-stream/duplex'
Require stack:
- /path/to/project/node_modules/node-browser-modules/index.js
- /path/to/project/node_modules/deppack/lib/shims.js
- /path/to/project/node_modules/deppack/lib/modules.js
- /path/to/project/node_modules/deppack/lib/deppack.js
- /path/to/project/node_modules/deppack/index.js
- /path/to/project/node_modules/brunch/lib/fs_utils/write.js
- /path/to/project/node_modules/brunch/lib/watch.js
- /path/to/project/node_modules/brunch/lib/index.js
- /path/to/project/node_modules/brunch/lib/cli.js
- /path/to/project/node_modules/brunch/bin/brunch
```

**Comment by paulmillr** [comment]
@Arcesilas try now.

**Comment by paulmillr** [comment]
You'll need to do `rm -rf node_modules package-lock.json && npm install`

**Comment by Arcesilas** [comment]
Thanks for your reply.

Now, I get:

```
00:46:54 - error: ENOSPC: System limit for number of file watchers reached, watch 'package.json'
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace. 
00:46:54 - error: Cannot read property 'close' of undefined
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace. 
00:46:54 - error: ENOSPC: System limit for number of file watchers reached, watch 'brunch-config.js'
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace. 
00:46:54 - error: Cannot read property 'close' of undefined
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace. 
```
while running `brunch build`. Probably another problem, though.

**Comment by paulmillr** [comment]
Interesting. How big is your project? Also, see https://github.com/gatsbyjs/gatsby/issues/11406

**Comment by Arcesilas** [comment]
It's empty... Only `brunch-config.js` and `package.json`

**Comment by Arcesilas** [comment]
Oh ! I also currently have a browser-sync with brunch 2 running.
