### ISSUE TITLE
Error: couldn't load config

### ISSUE THREAD

**Issue by jjalonso** [brunch/brunch#914]
Im trying to use brunch for first time. But look like no config file available.

Mac OS Yosemite 10.10.1
$ brunch -V
1.7.20
$ npm -v
2.1.18

```
Juan:todaybrunch jjalonso$ brunch new gh:ashleydavis/AngularJS-Skeleton
31 Jan 16:47:59 - log: Cloning git repo "git://github.com/ashleydavis/AngularJS-Skeleton.git" to "/Users/jjalonso/todaybrunch"...
31 Jan 16:48:02 - log: Created skeleton directory layout
31 Jan 16:48:02 - log: Installing packages...
bower angular#~1.2.22           cached git://github.com/angular/bower-angular.git#1.2.28
bower angular#~1.2.22         validate 1.2.28 against git://github.com/angular/bower-angular.git#~1.2.22
bower jquery#~2.1.1             cached git://github.com/jquery/jquery.git#2.1.3
bower jquery#~2.1.1           validate 2.1.3 against git://github.com/jquery/jquery.git#~2.1.1
bower angular#~1.2.22          install angular#1.2.28
bower jquery#~2.1.1            install jquery#2.1.3

angular#1.2.28 bower_components/angular

jquery#2.1.3 bower_components/jquery

Juan:todaybrunch jjalonso$ ls
README.md		app.js			bower.json		bower_components	index.html		npm-debug.log


Juan:todaybrunch jjalonso$ brunch build

Error: couldn't load config /Users/jjalonso/todaybrunch/config. Error: Cannot find module '/Users/jjalonso/todaybrunch/config'
  at Object.exports.loadConfig (/usr/local/lib/node_modules/brunch/lib/helpers.js:514:15)
  at Object.exports.loadConfig (/usr/local/lib/node_modules/brunch/lib/helpers.js:512:24)
  at initialize (/usr/local/lib/node_modules/brunch/lib/watch.js:453:20)
  at new BrunchWatcher (/usr/local/lib/node_modules/brunch/lib/watch.js:607:7)
  at module.exports.watch (/usr/local/lib/node_modules/brunch/lib/watch.js:663:12)
  at start (/usr/local/lib/node_modules/brunch/lib/index.js:13:33)
  at Command.<anonymous> (/usr/local/lib/node_modules/brunch/node_modules/commander/index.js:249:8)
  at Command.emit (events.js:98:17)
  at Command.parseArgs (/usr/local/lib/node_modules/brunch/node_modules/commander/index.js:472:12)
  at Command.parse (/usr/local/lib/node_modules/brunch/node_modules/commander/index.js:370:21)
  at Object.exports.run (/usr/local/lib/node_modules/brunch/lib/cli.js:49:13)
  at Object.<anonymous> (/usr/local/lib/node_modules/brunch/bin/brunch:11:22)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

**Comment by es128** [comment]
Try using an actual brunch skeleton. The repo you chose isn't one.

**Comment by jjalonso** [comment]
Mmmmm all the skeletons are not core, and use a lot of dependencies that i dont want, exist a posibility of use a core/base skeleton and actual ?

**Comment by jjalonso** [comment]
Neither

Brunch with bare livescript 10 ★	gh:gkz/brunch-bare-livescript	LiveScript, Less	Extremely simple skeleton without any frameworks

Simple Brunch with AngularJS	gh:ashleydavis/AngularJS-Skeleton		AngularJS v1.1.4 and jQuery v2.0.2

And this is working...

gh:monokrome/brunch-for-libs


The skeleton page is out of date. What about have a core brunch skeleton builtin ? is possible?

**Comment by jjalonso** [comment]
Juan:todaybrunch jjalonso$ brunch new gh:brunch/dead-simple

node.js:815
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Function.startup.resolveArgv0 (node.js:815:23)
    at startup (node.js:58:13)
    at node.js:906:3
