### ISSUE TITLE
config edits don't trigger reload

### ISSUE THREAD

**Issue by WillyPoteloin** [brunch/brunch#957]
When i edit brunch config file the Watcher print Watcher reloading but it does not.

**Comment by paulmillr** [comment]
Clarified the title.

**Comment by wiltzius** [comment]
I actually get a straightforward crash when editing the config file when the watch is running. Here's the snipped final few lines of the `brunch w --debug` output, and the ensuing stack trace:

```
$ brunch watch --debug
<...snip...>
28 Apr 20:57:24 - info: compiled 174 files into 6 files, copied 196 in 19344ms
< ... made a whitespace-only change to the brunch config file here ... >
28 Apr 20:58:32 - info: Reloading watcher...

/Users/wiltzius/Documents/welkin/dugong/node_modules/brunch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/polyfills.js:14
  chdir.call(process, d)
        ^
Error: Bad argument.
  at process.chdir (/Users/wiltzius/Documents/welkin/dugong/node_modules/brunch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/polyfills.js:14:9)
  at module.exports.watch (/Users/wiltzius/Documents/welkin/dugong/node_modules/brunch/lib/watch.js:706:13)
  at restart (/Users/wiltzius/Documents/welkin/dugong/node_modules/brunch/lib/watch.js:372:16)
  at reWatch (/Users/wiltzius/Documents/welkin/dugong/node_modules/brunch/lib/watch.js:380:16)
  at /Users/wiltzius/Documents/welkin/dugong/node_modules/brunch/lib/watch.js:387:14
  at EventEmitter.<anonymous> (/Users/wiltzius/Documents/welkin/dugong/node_modules/brunch/lib/watch.js:616:14)
  at EventEmitter.emit (events.js:95:17)
  at EventEmitter.<anonymous> (/Users/wiltzius/Documents/welkin/dugong/node_modules/brunch/node_modules/chokidar/index.js:135:15)
  at EventEmitter.FSWatcher._emit (/Users/wiltzius/Documents/welkin/dugong/node_modules/brunch/node_modules/chokidar/index.js:148:5)
  at EventEmitter.<anonymo%

**Comment by wiltzius** [comment]
It looks like the stack trace is truncated, but that's the full output I get in the console. If there's more logging somewhere that I can look at or turn on, I'd be happy to provide it.

**Comment by wiltzius** [comment]
I downgraded brunch from 1.8.2 to 1.7.20 (but didn't downgrade any of my plugins) and the crash no longer happens. So, looks like a regression. Let me know if I can provide more helpful information.

**Comment by kursion** [comment]
Hi guys,

I have the same issue. Any news since 20 days ? 

Best regards

**Comment by es128** [comment]
Just published a fix. Sorry for the delay.

**Comment by wiltzius** [comment]
thanks!
